### ISSUE TITLE
Webhooks access token modal displays incorrectly

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#124]
# Expected Behavior

Buttons of equal size when disabled

# Actual Behavior

The Buttons appear to be non-uniform in size when disabled.  Fix would be to add somewhere in the modal scss something like

.bx--modal-footer button.bx--btn {
    max-width: 50%;

# Steps to Reproduce the Problem

1. Click create webhook
2. Select a namespace
3. Click to + button to create access token

# Additional Info

**Comment by a-roberts** [comment]
@jessm12 has a fix for this so moving to in progress
