### ISSUE TITLE
Webhooks: the name of the JS file is changed

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/experimental#127]
# Expected Behavior
The extension works
# Actual Behavior
Get 404
# Steps to Reproduce the Problem
Install Webhook extension follow the guide

# Additional Info
The `annotations`: "tekton-dashboard-bundle-location" in `service` definition is not correct now.
it's "extension.50c02586.js" now.

So I guess we need document the issue, since I saw this in `rollup.config.js`
```
  output: [
    {
      dir: 'dist',
      entryFileNames: 'extension.[hash].js',
      format: 'esm',
      //sourcemap: true
    }
  ]
```

The `hash` will change every build.
Another option is remove the `hash`, not a good idea since the browser cache.

**Comment by dibbles** [comment]
Closing this issue as the hash problem has been/is being resolved (CLA problems have been holding out a number of PRs).

Additionally tests have been delivered that check the hash in the yamls match the hash produced by the build to try and reduce the chance of this problem re-occurring.

Changes in.....

https://github.com/tektoncd/experimental/commit/d8e4b3b3593b008be0ce09b6ad8b425eb731cd48
https://github.com/tektoncd/experimental/commit/21835e972782fce8552ecf16315da05b0116e0a4
https://github.com/tektoncd/experimental/commit/de0d081a10bdc0dee2e1de9e97e9ef0c00b877cf

The hash code modification requirement is detailed in the development.md (https://github.com/tektoncd/experimental/blob/master/webhooks-extension/DEVELOPMENT.md) and should not be seen as an issue by general users from now on (hopefully)
