### ISSUE TITLE
Webhooks table header looks like it has some border issues in firefox

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#130]
The webhooks table first and last column header look as though they are a couple of pixels different either in height or border compared to others.
 
Only seeing this in firefox...

![Screenshot 2019-07-03 at 13 19 27](https://user-images.githubusercontent.com/22838162/60590954-35cfa780-9d95-11e9-81e4-1430d2abcece.png)

**Comment by a-roberts** [comment]
Merged so closing
