### ISSUE TITLE
FR: support a git polling mechanism for eventing

### ISSUE THREAD

**Issue by castlemilk** [tektoncd/experimental#136]
I'd really be keen to see a git polling solution available to enable rapid prototyping and support for some more locked down environments which prohibit the exposure of a webhook endpoint for github to call. 

Support a git polling based approach would enabling the following use cases:

* enterprise/secured environments which don't expose a publicly available webhook endpoint, consequently unable to use the `GitHubSource` event source.
* enabling the development of local CI/CD pipelines for demonstration/validation purposes, where exposing a webhook is not available.

Not sure if this would be enabled through a standalone controller or an extension on the an exisiting experiment project. But it would involve a run loop with a set interval for polling the target repo. On detected changes it would create post the required `cloudevents` and `push`/`pull_request` payloads to the tekton listener, or even just directly create a `PipelineRun`.

**Comment by a-roberts** [comment]
Discussed with @dibbles and @mnuttall (sorry for taking so long to get to this!) - we think this is an excellent idea and would vastly improve our demo story too (e.g. for labs where people are just wanting to use github.com). It's obviously a very common use case...

We'd like to implement this in conjunction with our move to use triggers, which is how we plan to move the webhooks-extension out of experimental and into something for wider consumption and adoption.

**Comment by mnuttall** [comment]
Todo: look into https://github.com/fluxcd/flux re: polling

**Comment by mnuttall** [comment]
Also inlets.dev and https://caddyserver.com/docs/automatic-https as a means of passing webhooks across firewall boundaries.
