### ISSUE TITLE
Add filter labels to PipelineRuns triggered by a webhook

### ISSUE THREAD

**Issue by jessm12** [tektoncd/experimental#140]
We want to be able to filter within the dashboard `PipelineRuns` that have been triggered by a webhook through the extension. To do this we will need to add labels when each PipelineRun is triggered relating to the the repository and branch that it has originated from.

This issue relates to the backend work to add the relevant labels when we create a `PipelineRun` in our 'sink' code in response to a GitHub event.

Related to epic https://github.com/tektoncd/experimental/issues/37

**Comment by a-roberts** [comment]
I'll work this, same label as we add for a manually created PipelineRun I guess? 

@dibbles do you know what we have in mind?

**Comment by a-roberts** [comment]
This is now merged so closing 😄
