### ISSUE TITLE
PR test failures are ignored

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#164]
# Expected Behavior

PR unit tests when failing should make the PR as not having passed

# Actual Behavior

PR unit tests are showing as passed even though they have failed

# Steps to Reproduce the Problem

1. Go to a PR, go to the unit tests and see they have failures, e.g. https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_experimental/162/pull-tekton-experimental-unit-tests/1153958504990511105/?log#log

# Additional Info

**Comment by a-roberts** [comment]
I'll work on this and fix the tests.

**Comment by a-roberts** [comment]
@dibbles's fixed this as part of https://github.com/tektoncd/experimental/pull/166, closing
