### ISSUE TITLE
Webhooks Extension doesn't work with Knative 0.7.x - we need 0.7.1 support. 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/experimental#177]
Although we're moving off Knative we need interim support for 0.7.1. Hopefully it's as simple as @castlemilk suggests below. 

Package a dashboard and webhooks extension 0.2.1 release once this is available: 
- Tekton 0.7.x
- Knative 0.7.1

------------------------

Webhooks extension throws up errors when using Knative 0.7.0

When trying to create a webhook via the UI the following error is shown in the pod `github-controller-manager-0 -n knative-sources` repeatedly  

```
{"level":"warn","ts":"2019-07-30T08:08:59.281Z","caller":"sdk/reconciler.go:76","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: sink \"tekton-pipelines/webhooks-extension-sink\" (serving.knative.dev/v1alpha1, Kind=Service) contains an empty hostname","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/ghe-test"}
```

Also this error shows in the same log for the pod `github-controller-manager-0 -n knative-sources`  

```
{"level":"error","ts":"2019-07-30T08:13:00.311Z","caller":"sdk/reconciler.go:60","msg":"could not find &TypeMeta{Kind:,APIVersion:,} tekton-pipelines/ghe-test\n","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/ghe-test","stacktrace":"github.com/knative/eventing-contrib/pkg/controller/sdk.(*Reconciler).Reconcile\n\t/home/prow/go/src/github.com/knative/eventing-contrib/pkg/controller/sdk/reconciler.go:60\ngithub.com/knative/eventing-contrib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/prow/go/src/github.com/knative/eventing-contrib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/knative/eventing-contrib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/prow/go/src/github.com/knative/eventing-contrib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/prow/go/src/github.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/prow/go/src/github.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/prow/go/src/github.com/knative/eventing-contrib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

When getting the githubsource that it has created we are using `apiVersion: sources.eventing.knative.dev/v1alpha1`
However in the ksvc for the webhooks-extension-sink e are using `apiVersion: serving.knative.dev/v1beta1`

It appears that the two are incompatible as one uses alpha and the other uses beta 
Upgrading to being able to use Knative v0.7.0 would require Kubernetes v1.14 

It creates a webhook when using istio 1.2.2 and knative 0.6.0 so the issue must be with Knative 0.7.0 
As everything else uses Knative 0.6.0 it may be easier to keep using Knative 0.6.0 and not support Knative 0.7.0 for now

**Comment by castlemilk** [comment]
the resolution for this is to create both the alpha and beta CRDS in your cluster. I got this working by applying both of the following:

https://github.com/knative/serving/releases/download/v0.8.1/serving-alpha-crds.yaml
https://github.com/knative/serving/releases/download/v0.8.1/serving-beta-crds.yaml

then restart the `github-controller-manager-0` `Pod`

**Comment by mnuttall** [comment]
We plan to move off Knative under https://github.com/tektoncd/experimental/issues/40 rather than move up to 0.7 - even though as @castlemilk points out, it may not be a lot of work to do so.

**Comment by a-roberts** [comment]
@Megan-Wright see https://github.com/tektoncd/experimental/blob/master/webhooks-extension/pkg/endpoints/webhook.go#L29 for our usage of `alpha`, I spoke with @vdemeester about versions and it looks like 0.7.1 is the current knative version used in the openshift operator atm
