### ISSUE TITLE
Vulnerability scan

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#181]
The application should likely be scanned for vulnerabilities.  I am not sure on any recommended open source tools that could be added into the automated build and test - IBM has an appscan vulnerability scanning solution so perhaps could at least perform some manual scans??

**Comment by nirvana-flame** [comment]
AppScan is good tool for static/dynamic scaning for vulnerabilities.

snyk.io is great openSource vulnerabilities scaning tool.
