### ISSUE TITLE
On deleting the last webhook, selecting an item for target pipeline sends me to the top of the page

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#191]
# Expected Behavior
It shouldn't - it doesn't if there's no notification at the top of the page

# Actual Behavior
On selecting an entry with the notification up, you're sent to the top of the page again

# Steps to Reproduce the Problem

1. Create a webhook
2. Delete the webhook
3. Try to create a new one, selecting, for example, a target pipeline namespace - observe the problem

See https://github.com/tektoncd/experimental/blob/master/webhooks-extension/src/components/WebhookCreate/WebhookCreate.js#L500 which mentions the only scrollTo:  ` {this.state.showNotification && window.scrollTo(0,0)}`

**Comment by jessm12** [comment]
PR: https://github.com/tektoncd/experimental/pull/193

**Comment by a-roberts** [comment]
Merged so closing
