### ISSUE TITLE
Webhooks extension returns HTTP 403 Forbidden on OKD 

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#204]
When installing as per the openshift guidelines onto an OKD cluster, the webhooks-extension service cannot be reached - returning a HTTP 403 Fobidden response.

This is because the ClusterRole yaml does not have the following:

```
- apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
```

We either need a separate openshift install yaml, where the ClusterRole has the additional snippet given above, or an update to the openshift instructions to advise on the required additional steps.

It may be possible to come up with a single command to patch the ClusterRole, I tried using `oc patch clusterrole tekton-webhooks-extension-minimal --patch '{"rules":[{"apiGroups": ["security.openshift.io"], "resources": ["securitycontextconstraints"], "verbs": ["use"]}]}' --type='merge'` but that seemed to overwrite the other settings in the clusterrole (rather than merging).

For now, we have successfully accessed the webhooks UI by doing the following after following the openshift webhooks-extension instructions:

1. After installation, ensure pods are running
2. `oc edit tekton-webhooks-extension-minimal`
3. Add the following:
```
- apiGroups:
  - security.openshift.io
  attributeRestrictions: null
  resources:
  - securitycontextconstraints
  verbs:
  - use
```
4. save the update
5. restart the webhooks-extension pod

**Comment by a-roberts** [comment]
FYI I've just manually added this file into our release https://github.com/tektoncd/dashboard/releases/download/v0.1.1/openshift-webhooks-extension.yaml as another team has been seeing this problem, whoever works on this needs to update the release process to include this file when we do release again

**Comment by a-roberts** [comment]
@dibbles is adding this file as part of his work involving readme changes (mentioning installing on openshift, which has highlighted the lack of a release yaml in source control - so it'll be added with the above configuration set)

**Comment by dibbles** [comment]
fixed in https://github.com/tektoncd/experimental/pull/210 - new openshift yaml file added for installing "nightly" builds
