### ISSUE TITLE
Rebase webhook sink on trigger 

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/experimental#209]
# Expected Behavior

Webhook sink (receiving the webhook event and executing the pipeline) should be implemented based on the tekton/trigger 

# Actual Behavior

The webhook in tekton / experimental has been implemented earlier than the tekton / trigger become useable.  It has its own code to define the webhook and process the webhook event.  These code should be removed and / or rebased on the trigger.

There are 2 components in the current webhook.

1. Webhook component provides REST APIs that process the webhook record CRUD.  The webhook record has information that associates the webhook event to a specific tekton pipeline and information that is required to execute the tekton pipeline.  The webhook component configure the webhook in the github  when the webhook record is configured.
  
1. Sink component receives the webhook event and starts the tekton pipeline specified in the webhook record.

# Steps to rebase the webhook

- Remove the sink component
- Define triggerTemplete for the currently supporting pipelines
- In the Webhook component when the webhook record is created
   - Create webhook in the github
   - Define triggerBinding for the specified pipeline with the necessary information from the REST API embedded.
   - Create the eventListener with the triggerBinding and the triggerTemplate
   - Expose the eventListener (ingress, route, and etc..) 
 - In the Webhook component when the webhook recored is deleted, clean up the resource and configuration done  at the create.
 

# Additional Info

**Comment by dibbles** [comment]
So after educating myself and drawing some pictures... it is basically what Aki said, although I have tried to pull together issue numbers where required trigger code does not exist yet - and am working with @ncskier on ideas around missing function for reporting status via monitor task.

[triggers.pdf](https://github.com/tektoncd/experimental/files/3601433/triggers.pdf)

**Comment by dibbles** [comment]
I'm going to start trying to switch over to triggers
