### ISSUE TITLE
Delete modals inconsistent

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#211]
https://github.com/tektoncd/experimental/pull/203 changed the way the delete modal buttons look and their text ..... this now means they are inconsistent with the delete secret modal on the create webhook page.

personally, I'd prefer it as put back to green and red, centralised text, vertically aligned centrally as well, and in the smaller font...... changing the buttons was never in the scope of the issue that pull request 203 was raised to address.

**Comment by carlos-logro** [comment]
Hi @dibbles, on my end the the modals look quite consistent. Also, in regards with the text in the action buttons the default carbon design has them on the left although smaller font. If we can agree where to have them & the size I don't mind doing the adjustment. @AlanGreene 

<img width="795" alt="Screen Shot 2019-08-15 at 2 05 08 PM" src="https://user-images.githubusercontent.com/49996607/64022324-f2c75180-cb03-11e9-8290-a64af176c3aa.png">
<img width="780" alt="Screen Shot 2019-08-30 at 8 54 37 AM" src="https://user-images.githubusercontent.com/49996607/64022325-f2c75180-cb03-11e9-815f-5086a22eb6eb.png">

**Comment by carlos-logro** [comment]
Oh I read wrong, I thought you meant the delete modal in the secret page. That being said the delete secret modal in the webhook create page should be updated to be consistent with the other modals.

**Comment by carlos-logro** [comment]
PR #300 fixed this but also removed some necessary styles that made the disabled create button render incorrecly. That being said, PR #316 fixes that minor error.

thus closing this issue.

/close
