### ISSUE TITLE
Use "Unknown" rather than "??????" for pipelinerun status on pull request

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#220]
# Expected Behavior

When the monitor task adds the status table to a pull request, "Unknown" should be reported for those pipelineruns which have not yet completed.

A user can currently set the success comment and failure comment when creating the webhook.  They should also therefore be able to set this "timeout" status message.

Docs also need updating as they explicitly mention the "??????" status code - might also be an image containing said status.

# Actual Behavior

Currently "?????" is reported as the status for unknown pipelinerun results where the monitor reaches its timeout.

# Steps to Reproduce the Problem

1. Create webhook with a long running pipelinerun (more than 30mins to complete - or edit the monitor task to simulate the situation by reducing the timeout)
2. Create a pull request on the repository
3. Not the resultant comment in the pull request, table shows ??????

# Additional Info

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/experimental/pull/301

**Comment by a-roberts** [comment]
It's configurable and defaults to unknown so closing
