### ISSUE TITLE
Comments deleted on pull request by monitor task

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#221]
# Expected Behavior

Once the pull request has been put into pending status, I should still be able to add comments to the pull request, and have those comments persist after the status is subsequently updated again by the monitor task.

# Actual Behavior

The monitor task uses a pipelineresource of type pullrequest to update the pull request with the result of the pipelineruns.  It pulls down the pull request when the monitor task begins, and then updates that local copy of the pull request once the monitor task completes and send the update to github.

It appears that any comments added to the pull request in github after the monitor task has started are deleted after the monitor task uploads on completion. 

# Steps to Reproduce the Problem

1. create webhook
2. create pull request to trigger webhook
3. once pull request status shows pending (so you know the task monitor is running), add some comments onto the pull request
4. when the monitor task finishes, and the pull request status is set to passed or failed, you will see your comments have been deleted.

# Additional Info

**Comment by vtereso** [comment]
See: https://github.com/tektoncd/pipeline/issues/1286#issuecomment-534746540 and https://github.com/tektoncd/pipeline/pull/1408. This should be available within the 0.8 Tekton release.

**Comment by ncskier** [comment]
Pipelines v0.8.0 is out now, and I just tested this with our latest code. The comments that I made in the pull request were not overwritten by the monitor task.
/close
