### ISSUE TITLE
Monitor task uses git api to move pull request to pending

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#222]
The monitor-result-task has been coded to use the git api endpoint directly to move the pull request into pending state at the start of pipelineruns.

The current implementation of the monitor task only uses the "pullrequest" pipelineresource to update the pull request at the end of the task ..... it doesn't appear to be able to upload the pull request updates at multiple points in time.

Investigate if there is a better way of using the pullrequest pipelineresource to download and upload.

**Comment by vtereso** [comment]
As of now, the pull request functionality doesn't support this: https://github.com/tektoncd/pipeline/blob/master/cmd/pullrequest-init/main.go#L31. Although `PipelineResources` are unlikely to make beta, the underlying images (e.g. generated by `ko` from the above) can be used as tasks in much the same way. We could add an optional parameter to the download flag, which would set the status.
