### ISSUE TITLE
Pipelines dropdown sometimes isn't populated

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#225]
# Expected Behavior

After selecting a target namespace on webhook creation, the pipelines dropdown should populate with available choices.

# Actual Behavior

Not sure if anyone else is seeing this but, on my openshift (possibly network related), when creating a second webhook, the dropdown for pipelines doesn't always seem to populate....
need to see if anyone can reproduce and look into this....

# Steps to Reproduce the Problem

1. create two webhooks on same repo, different namespaces
2. sometimes on the second one, the pipelines dropdown is not populated
3.

# Additional Info

**Comment by carlos-logro** [comment]
Tried to reproduce the problem but could not manage to it. Tried it in Safari, Chrome & Firefox.

**Comment by ncskier** [comment]
Unfortunately, I was not able to reproduce this error either. I tried multiple times on Chrome. I tested on D4D and pulled the latest code from master today, installing with `npm ci`, `npm run build_ko`, `ko apply -f config/`.
