### ISSUE TITLE
Deployment and Service are missing `namespace: tekton-pipelines`

### ISSUE THREAD

**Issue by TatchNicolas** [tektoncd/experimental#231]
# Expected Behavior

I run into the problem when trying Webhook extention.

Following [the doc](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/InstallReleaseBuild.md), `Webhook` should be in the side bar.

# Actual Behavior

After restarting the dashboard pod, `Webhook` does not showing up becuase `webhook-extention` is not in `tekton-pipelines` namespace

```
kubectl get pods --namespace tekton-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-dashboard-7d6c4d746d-g6bgt              1/1     Running   0          36m
tekton-pipelines-controller-857f9f4dd9-2vl2j   1/1     Running   0          36m
tekton-pipelines-webhook-844f844f47-httfx      1/1     Running   0          36m
```

# Steps to Reproduce the Problem

1.  Setup a cluster, install Istio and Knative 
2. `kubectl apply --filename https://github.com/tektoncd/dashboard/releases/latest/download/webhooks-extension_release.yaml`
3. `kubectl get pods --namespace tekton-pipelines`

# Additional Info

I figured out the cause, `Deployment` and `Service` for `webhook-extention` were somehow not in `tekton-pipeline` namespace but `default`.

It seems the manifest available(as of the time this issue created) from https://github.com/tektoncd/dashboard/releases/latest/download/webhooks-extension_release.yaml does not have `namespace: tekton-pipelines` for them. 

I wanted to file PR but not familiar with the project structure and which file corresponds...

If the missing namespace is only the case with me, plz ignore this :bow:

**Comment by a-roberts** [comment]
Hey @TatchNicolas, cheers for reporting this!

https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/extension-deployment.yaml I fixed this on master as part of https://github.com/tektoncd/experimental/issues/202, could you please apply the latest yaml from master instead?

`kubectl apply -f https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml` or `https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/release/openshift-tekton-webhooks-extension.yaml` please depending on your platform

We haven't backfixed any uploaded release yamls so far (we had planned to do a 0.6.0 release soon with the above fix in but there are other bugs we're still working on!)

**Comment by TatchNicolas** [comment]
Thank you @a-roberts, it worked with the lastest manifest!
Sorry I missed the issue and did not know it was already fixed...

To be precise with the following command(just for those who might see this issue)

`kubectl apply -f https://raw.githubusercontent.com/tektoncd/experimental/master/webhooks-extension/config/release/gcr-tekton-webhooks-extension.yaml`

And thanks again for your fix!
