### ISSUE TITLE
Prevent deployment from occurring during Pull Request builds

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#236]
Builds driven by Pull Requests should not result in a new deployment. We need to pass the fact that a PipelineRun was triggered by a PullRequest into the PipelineRun, and then use that to gate deployment. This could be done via an environment variable, and the conditional syntax introduced in Tekton 0.6.

We need to be able to act on two variables so as to construct guards of the form, 
```
if branch==master && !pull_request { 
  // create deployment, publish image, etc 
}
```

**Comment by mnuttall** [comment]
Moving this over to @vtereso - thank you Vincent

**Comment by a-roberts** [comment]
@vtereso I spoke with @mnuttall about this, so to summarise what we'd like to do as a "first pass" is as follows.

**Gating deploys for "simple pipeline" is the first thing to experiment with.**

1) Determine if it's a pull request (if so, don't deploy, just build and run any tests)
2) Determine what branch we are on (are we on master? Great, something's likely been merged in from, say, a test/dev branch, so it's good to deploy)

Next we should be looking at creating pull requests of our own into the Kabanero pipeline repositories to update the Codewind and Appsody pipelines with the same gating logic.

Eventually (I'm working on the validate task atm so in a good position to do this), we can add the gating logic in here.

**Comment by vtereso** [comment]
https://github.com/kabanero-io/kabanero-pipelines/pull/73
https://github.com/pipeline-hotel/example-pipelines/pull/8
