### ISSUE TITLE
Test and recommend newer Istio version (1.1.14)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#238]
Have a look at https://istio.io/about/notes/1.1.14/, which mentions an important security fix (so does 1.1.13), we currently suggest using Istio 1.1.7.

Noticed by accident when looking into https://github.com/tektoncd/experimental/issues/235.

Testing would include with knative 0.6.0, Tekton Pipelines master (soon to be 0.7.0) and the latest Tekton Dashboard.

Yes, we do eventually want to remove our reliance on knative/istio for webhooks (in favour of triggers) but that may take a while and this *could* 🤞 be an easy suggestion.

**Comment by carlos-logro** [comment]
knative: v0.0.6
docker: 2.1.3.0
kubernetes: 1.14.6
dashboard: 0.2.0
versions in which i was able to create a webhook, commit changes & see a successfully triggered PipelineRun: 
1.1.8
1.1.9
1.1.10
1.1.11
1.1.12
1.1.13
1.1.14
1.1.15
1.1.16

**Comment by a-roberts** [comment]
Thanks @carlos-logro (looping back on this while cleaning up issues), could you do a PR to mention those versions we've tried please?

It's useful information to know and users are welcome to install with, say, Istio 1.1.16.

I realise these guidelines will eventually change for OpenShift 4.2 and our Triggers story but it's useful to have in the meantime.
