### ISSUE TITLE
Webhooks extension PipelineRun sometimes doesn't have PipelineResources ready in time

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#240]
# Expected Behavior

PipelineRuns should be reliably constructed and kicked off

# Actual Behavior
Suffers from https://github.com/tektoncd/dashboard/issues/469 also, it's not 100% of the time though (committed again and I didn't see the issue)

# Steps to Reproduce the Problem

1. Create a webhook
2. Push code to that repository
3. Observe that on occasion (first time for me the problem observed, second time it was fine) the PipelineRun fails because the PipelineResources don't yet exist

**Comment by a-roberts** [comment]
Can't reproduce this in 30 webhook push events 🤔 suggesting this not hold up our upcoming release but something we should certainly look into (I'm using a particularly slow OpenShift cluster as I believe @dibbles was when importing resources and noticed this problem)

**Comment by a-roberts** [comment]
Asked about this in Slack, @dibyom mentioned https://github.com/tektoncd/pipeline/pull/1324 as a potential solution and Andrew's noticed this too for Jenkins X happening

I'm gonna reopen this

**Comment by ncskier** [comment]
/assign
Just to clarify, the goal of this issue is now to embed the PipelineResource in the PipelineRun that the webhooks extension is creating. Correct?

**Comment by ncskier** [comment]
We don't have `github.com/tektoncd/pipeline` in our `Gopkg.toml` file. I'm going to add it because we will explicitly need to be on a version including https://github.com/tektoncd/pipeline/pull/1324.

**Comment by ncskier** [comment]
PR ready, but holding on this issue. See [this](https://github.com/tektoncd/experimental/pull/296#issuecomment-543756159) comment.
/unassign

**Comment by a-roberts** [comment]
Closing this off, we now run Trigger templated code through our managed EventListener, we could update our pipeline examples in the hotel (embedding the resource in the PipelineRun spec) but that's completely separate from this really and can be done whenever we like, closing
