### ISSUE TITLE
Triggers: Write Task with options to create/delete github repo webhook

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#241]
Write a task in yaml that allows creation or deletion of a github repository webhook - code can predominantly be taken from https://github.com/tektoncd/triggers/blob/master/docs/create-webhook.yaml and then extended.

The yaml can be stored under a config/triggers_prototype folder.

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/248

**Comment by a-roberts** [comment]
Merged so closing
