### ISSUE TITLE
Triggers: Write Task with options to create/delete Ingress

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#242]
Write a task in yaml that allows creation or deletion of an Ingress endpoint for an event listener take code from https://github.com/tektoncd/triggers/blob/master/docs/create-webhook.yaml and then extended to allow for deletion.

The yaml can be stored under a config/triggers_prototype folder.

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/249

**Comment by a-roberts** [comment]
Note that to get this working on Docker Desktop OK, I needed to install nginx as the Ingress controller:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud-generic.yaml
```
 Then curling the Ingress routes to my backend listener svc correctly.

**Comment by a-roberts** [comment]
Merged so closing
