### ISSUE TITLE
Triggers: Create validate service and image

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#245]
With each trigger in the eventlistener we will specify the validation task that needs running to check whether or not the trigger should fire/create pipelineruns etc...

The validation task will need to validate the webhook is "authentic" (should be able to reuse the current triggers validation task example) and then validate a set of circumstances.

Current validation would need to be:

event repository matches input param
event type is push or pull request

The yaml can be stored under a config/triggers_prototype folder.

**Comment by a-roberts** [comment]
I'll work on this, have PRs open for Ingress and Webhooks atm but don't see any trouble happening over there. Shouldn't be much code 🤞 and I spoke with @vtereso about this initially when figuring out if we needed anything to be changed in Triggers - he's suggested the validate task is the way to go, so we have ample options to get feedback too

**Comment by a-roberts** [comment]
Revisiting this to use the validation service/interceptor next to avoid PPP

**Comment by a-roberts** [comment]
I'm gonna put this back on the backlog for anyone to pick up, we're looking to have example pipelines to use next for triggers (so in terms of priority, this comes after that)

**Comment by a-roberts** [comment]
For anyone picking this up, see

https://github.com/tektoncd/triggers/pull/144  and https://github.com/tektoncd/triggers/pull/140

**Comment by a-roberts** [comment]
I'm going to pick this up, my other PRs/issues are on hold (working with @dibbles so they may need some tidying up/addressing based on findings)

Dibyo's PR is merged and I have an example to be following

**Comment by a-roberts** [comment]
Note the new design involves a service that references an image we're going to have to build and maintain

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/290

**Comment by a-roberts** [comment]
Merged so closing
