### ISSUE TITLE
Pull Request webhook should only fire on creation(?)

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#250]
# Expected Behavior

Pipelines should not be fired when pull request closed, labelled, assigned etc... Only on creation or underlying code updated 

# Actual Behavior

Pipelines triggered on any pull request action

# Steps to Reproduce the Problem

1. configure webhook
2. create pull request (pipelines triggered)
3. perform some actions on pull request eg. close (pipelines triggered)

# Additional Info

**Comment by mnuttall** [comment]
The GitHub 'Pull Request' category includes, 
> Pull request opened, closed, reopened, edited, assigned, unassigned, review requested, review request removed, labeled, unlabeled, or synchronized.
We only want a PipelineRun on a few of these events. New PipelineRuns are required when a PR is opened, or new code is pushed to its associated branch, or a closed PR is reopened. We don't want to address this issue until https://github.com/tektoncd/experimental/issues/247 is delivered and we're using Triggers to initiate webhook'd pipelines. At that point we have two options:
- Filter unwanted PR events out in Validation, or
- Filter unwanted PR events out in Pipelines. 

Doing this in validation is probably ok - although it could give us a GitHub vs GitLab problem down the road.

**Comment by vtereso** [comment]
With the move to Triggers (under the current architecture), we need to have a validator/interceptor for events. With multiple interceptors, we could have authentication for one inteceptor and repo/event matching in other. A single interceptor could also do this all in one, but would be less modular (in case this feature isn't available when this is picked up). Although we could have one large service to authenticate for both GitHub and GitLab (or any other provider), separating them might be easier to manage. In any case, once we tackle this I don't think we should have any blockers.

**Comment by akihikokuroda** [comment]
Here is the doc for the pullrequest action. 
 https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by akihikokuroda** [comment]
Check the `action` of the pullrequest and
process: `opened`,  `reopened`, ignore: `assigned`, `unassigned,` `review_requested`, `review_request_removed`, `labeled`, `unlabeled`, `edited`, `closed`, `ready_for_review`, `locked`, `unlocked`

> new code is pushed to its associated branch

 should be in the pushreqeust

**Comment by AlanGreene** [comment]
Should we also include `synchronize` (when PR commits are updated)?

**Comment by akihikokuroda** [comment]
Probably,  I don't know what this mean yet, though.

> While webhooks are also triggered when a pull request is synchronized, Events API timelines don't include pull request events with the synchronize action.

**Comment by AlanGreene** [comment]
I think it's referring to this API to list timeline events for a PR since it already has a 'committed' event for that case and 'synchronized' wouldn't make sense: https://developer.github.com/v3/issues/timeline/

I just verified I receive a webhook payload with `action: synchronized` when I push changes to a PR.

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/experimental/pull/354
