### ISSUE TITLE
Better description for the webhook fields - some are inaccurate

### ISSUE THREAD

**Issue by mtamboli** [tektoncd/experimental#251]
# Expected Behavior

This problem is for creating webhook using Tekton Dashboard. It would help to have more helpful description for the fields.  Also, some of the description are incorrect/out of order. Screenshot pasted below.

# Steps to Reproduce the Problem
![image](https://user-images.githubusercontent.com/29490950/65340349-03fffd00-db9c-11e9-8aea-268e1ee69161.png)

1. Hover over all the fields to look for the description
2.
3.

# Additional Info

**Comment by dibbles** [comment]
https://github.com/tektoncd/experimental/pull/260

**Comment by mtamboli** [comment]
@dibbles Thanks for looking into this. There are couple of things which will help.

1. Having a link from the Webhooks page to the doc for explanation on each field.
2. It would help to know a bit explanation on `Access Token` field. We were expecting to be able to pick up secret defined in a separate tab. Good to explain that this is the token generated in the same git repository as repository URL.
3. Docker Registry:  Finding the correct syntax for this field was a bit of challenge. So it will be helpful to know examples of internal registry as well as docker hub. Webhook did not like if you provide https://index.docker.io/<namepspace>. It had to be index.docker.io/<docker_id>
For example:
Internal registry:  docker-registry.default.svc:5000/<namespace>
Docker Hub: index.docker.io/<docker_id>

We were also not sure if the image name need to be provided or not. So having some example will certainly help.

**Comment by mtamboli** [comment]
@a-roberts I use tekton dashboard which is installed as part of Kabanero. I will need to get access to updated version  of dashboard to verify it. If I am not able to verify, I will close it and reopen later if there are any new issues.
