### ISSUE TITLE
Option of initiating webhook in Tekton Dashboard manually without any code change GitHub event

### ISSUE THREAD

**Issue by mtamboli** [tektoncd/experimental#253]
# Expected Behavior

It would be nice to have option of initiating a webhook run manually from the Tekton Dashboard with default master branch. Currently, you can start a Pipelinerun but it is not straight forward as you need to provide other inputs. But initiating the webhook manually may not need any extra inputs.

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by mnuttall** [comment]
HI @mtamboli thank you for raising this idea. Webhooks can be manually triggered from within GitHub's 'settings' which you might find a convenient approach today. Manual webhook initiation would require us to drive GitHub to re-issue the webhook. This would be a nice thing to have, and we'd be delighted if someone wanted to pick this up to work on.
