### ISSUE TITLE
The secure route for webhook API is incorrectly reset to unsecure 

### ISSUE THREAD

**Issue by chunlongliang-ibm** [tektoncd/experimental#254]
The route created for webhook is insecure by default (i.e., no TLS, and plain http). I edit the route to check "secure route", and TLS works (Github can post to the webhook API over TLS). However, after couple minutes, the "secure route" is unchecked, and TLS connection fails. You can check the "secure route" to get it working again, but the box will be automatically unchecked again. 
How do I can save "secure route" permanently? 

The steps for recreation:
1. create webhook
2. edit route to enable "secure route"
3. wait for couple minutes, the check mark will be gone.

**Comment by chunlongliang-ibm** [comment]
should we enable "secure route" by default?

**Comment by mnuttall** [comment]
The work we're doing under https://github.com/tektoncd/experimental/issues/40 will allow us to stop using this code path. Thank you for raising the issue, but I'm going to close it since we'd rather not invest further time in the knative-based code at this point.
