### ISSUE TITLE
specify docker registry format when creating a webhook in tekton console

### ISSUE THREAD

**Issue by tam512** [tektoncd/experimental#257]
# Expected Behavior
- When creating a new webhook in tekton console, the `Docker Registry` for `Target Pipeline Settings` should be able to accept both formats of `https://` or `without https`.  Right now it only works when entering the registry without  the `https://` such as `index.docker.io/<docker hub id>`
- If entering docker registry as `https://index.docker.io/<docker hub id>` the tekton pipeline runs will fail with error
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "https://index.docker.io/<docker hub id>/njsloopback-sample:73a7e56": creating push check transport for https: failed: Get https://https/v2/: dial tcp: lookup https on 172.20.0.1:53: no such host
```
- If https format is not supported, then there should be a sample in the registry text box field or a clear format description when hover the mouse point over the `i` next to the Docker Registry 

# Actual Behavior
When creating a new webhook, the description for `Docker Registry` is `The docker register to push images to` as following
![Screen Shot 2019-09-23 at 2 10 01 PM](https://user-images.githubusercontent.com/22480038/65454996-e0db8480-de0b-11e9-921b-2fcd8d28523c.png)

# Steps to Reproduce the Problem

1. in tekton console, create a new webhook, the `Docker Regsistry` is in the last row of the panel

# Additional Info

**Comment by mnuttall** [comment]
docker registry entries could in theory be in at least seven formats:
- http://index.docker.io/foo
- index.docker.io/foo
- foo
- https://index.docker.io/foo
- http://my.repo/foo
- https://my.repo/foo
- my.repo/foo

We need to understand which we can accept, check they work, and reject the rest.
