### ISSUE TITLE
Webhooks with a name of "." do not delete 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/experimental#269]
# Expected Behavior
Webhooks extension
Deletes a webhooks extension with the name "."

# Actual Behavior
Unable to delete a webhook with the name of "." 
Get a 405 Method not allowed error 

# Steps to Reproduce the Problem

1. Create a webhook called "."
2. Try deleting it 

# Additional Info
![Screenshot 2019-09-27 at 14 21 47](https://user-images.githubusercontent.com/32342288/65772467-2bbe0a80-e132-11e9-948f-5b106dbc75a6.png)

**Comment by a-roberts** [comment]
Hmmmmmmmmm, not really the best of webhook names so surely our regex should be checking for alphanumeric chars as well in it

**Comment by Megan-Wright** [comment]
Fixed with PR: https://github.com/tektoncd/experimental/pull/274 so closing
