### ISSUE TITLE
Test and document webhooks usage with OpenShift internal registry

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#284]
Most of our testing has used Dockerhub as the target docker registry. Use this item to understand and document what's required to publish images to, and deploy them from, the RedHat OCP 3.11 or 4.2 internal docker registry. 

See https://blog.openshift.com/remotely-push-pull-container-images-openshift/ for additional information. 

In an internal Slack conversation, a colleague wrote, 
> for example, I did right now a docker push into IBM Cloud + OpenShift using `docker push docker-registry-default.polaris-ocp-hexxxxx-0001.us-south.containers.appdomain.cloud/<id>/app:v1`, but then in my app-deploy.yaml I had to use `applicationImage: docker-registry.default.svc:5000/<userid>/app:v1`. 

> because the values for docker push vs applicationImage are different ... the workaround I found is to do  build --tag <docker_push_tag>, and then manually do a docker push <docker_push_tag>, and then deploy -t <applicationImage_tag>

Is this a real problem? Does it affect Pipelines that build and deploy images in a single step? Investigate and document. 

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#image-stream-mappings may offer some clues. 

Our colleague adds, 
> Tekton is always pushing to the local cluster it's running at, so then the URL to push becomes the same local URL to pull during deployment.  This will fail as soon as we try to make Tekton push into a remote OpenShift registry, since it will hit this: https://github.com/appsody/appsody/issues/410  (unless the tekton dashboard can gather the two separate URLs, one to push, one to deploy)
Perhaps there will be even a problem with a local 4.x cluster, as per one of the comments.

**Comment by akihikokuroda** [comment]
So far, I don't see any issue in using the Openshift internal registry.  I used "java-microprofile-build-deploy-pipeline" installed by Kabanero and specified "docker-registry.default.svc:5000/kabanero/" as the docker registry in the webhook creation.

Additional information in the webhook creation:
- Repository URL: created by the appsody init in GHE
- Access Token: GHE access token
- Namespace: kabanero
- Service account: appsody-sa

**Comment by akihikokuroda** [comment]
I opened the issue https://github.com/kabanero-io/docs/issues/133 in kabanero/doc.
