### ISSUE TITLE
GitHub webhook ping 404 error

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#294]
# Expected Behavior
I expect that when a webhook is created in GitHub, GitHub will verify that the webhook points to the proper URL by sending a ping request and receiving a valid response. The GitHub webpage indicates this success with a green checkmark next to the webhook.

# Actual Behavior
Sometimes, the ping request fails with a 404 error, and I see a red "x" next to the webhook on the GitHub webpage. I think that this is happening because there is a race condition between GitHub sending the ping event and the webhook-extension setting up the sink kservice.

# Steps to Reproduce the Problem

1. Create a GitHub webhook using the webhook-extension.
2. Open the GitHub webpage for your project, and navigate to "Settings" > "Hooks".
3. View the red "x" next to your webhook; click on the webhook for more details about the recent deliveries.

# Additional Info
- I do not see this happening every time I set up a webhook.
- The webhook still functions as expected even though the initial ping event failed.
- When I redeliver the ping event from the GitHub webpage, it succeeds after the initial failure.

**Comment by a-roberts** [comment]
Yeah, while we don't have a release out there using Triggers (where we won't see this issue) I think it's worth spending a little time on seeing if there's a quick fix for this, happens to me plenty of times too on a "first webhook" event. 

Worst case scenario we mention it in the docs (one should retrigger the payload if they get a 503 back too indicating there's no sink ready yet)

I'll add to the backlog

**Comment by ncskier** [comment]
/assign
I took a quick look at this, and since knative is setting up our webhook, it doesn't look like something that we can quickly fix.

This isn't a breaking bug, and it will be resolved with #243. So, I've mentioned it in the docs with this PR https://github.com/tektoncd/experimental/pull/308.

**Comment by a-roberts** [comment]
Yeah, I agree so let's close with the doc, thanks for the PR @ncskier
