### ISSUE TITLE
Plumbing update for nightly builds

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#339]
config/latest/gcr-tekton-webhooks-extension.yaml refers to gcr.io/tekton-nightly/interceptor:latest which is not yet being published.

test/presubmit-tests.sh starts with

source $(dirname $0)/../../vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
It is through the plumbing scripts that our overnight images are published to gcr. A plumbing update is required in order to publish the new interceptor image.

**Comment by a-roberts** [comment]
Pretty sure I just need to change the word `sink` to `interceptor` for publish-images.sh, will test

Need a followup issue to fix the release pipeline as well

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/348

**Comment by a-roberts** [comment]
Job finished, PR merged

```
adams-mbp:webhooks-extension aroberts$ docker pull gcr.io/tekton-nightly/interceptor:latest
latest: Pulling from tekton-nightly/interceptor
9ff2acc3204b: Already exists
72164b581b02: Already exists
5891cb5a3a52: Pull complete
Digest: sha256:28729c957cf70065f49557772254f341232ab6e4199a264b5c6d2690ecc1c877
Status: Downloaded newer image for gcr.io/tekton-nightly/interceptor:latest
gcr.io/tekton-nightly/interceptor:latest
```

Had a few layers locally as I built it in the first place, closing
