### ISSUE TITLE
Labels getting deleted from pull requests by the monitor task

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#340]
It looks like we do not preserve labels/data on the pull request when the monitor task does its upload - this might be as simple as copying the /workspace/pull-request/labels directory to /workspace/output/pull-request/labels ????

1. To recreate the bug create a pull request - let the pipelinerun finish
2. Add a label to the pull request (causing a pipelinrun to start)
3. Cancel the pipeline run in the dashboard and refresh the pull request to see the label disappear

**Comment by akihikokuroda** [comment]
I added the changes for this in the same PR https://github.com/tektoncd/experimental/pull/357 as https://github.com/tektoncd/experimental/issues/334

**Comment by a-roberts** [comment]
Taking a look to verify now

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/69066467-436e8c80-0a19-11ea-8574-f452be2a45c3.png)

Confirmed this no longer happens so we're all good on master, I will add the fix to the released 0.2.1 yaml
