### ISSUE TITLE
Webhooks on AWS

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#343]
Use this issue to test Tekton dashboard and webhooks extension to receive and act on webhooks from github.com to a Tekton hosted on public AWS. This may result in code changes and should result in a documentation update to note what was learned on the way.

**Comment by akihikokuroda** [comment]
By creating the ingress in the EKS, the ALB (application load balancer) is created as the ingress.  It can  be used to route the webhook events and the dashboard requests.

**Comment by akihikokuroda** [comment]
Can I get the AWS account to work for this issue?

**Comment by mnuttall** [comment]
@akihikokuroda I've just seen this, and have kicked off an internal request via email.

**Comment by akihikokuroda** [comment]
So far,I could set up webhook in AWS EKS.  The webhook notification comes in the eventlistner but the validation is failing.

The changes that are necessary to make the ingress work in the EKS are:
1. create webhook with a dummy webhook url.
2.  add 2 annotations in  the ingress 
```
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      kubernetes.io/ingress.class: alb
```
3. add `serviceType` with the value `LoadBalancer` in the eventlistener CR to make the event listener service type `LoadBalancer`
4. edit the ingress and put the assigned address as the host address
5. edit github webhook and set the assigned address

**Comment by akihikokuroda** [comment]
The validation is failing with 
```
2019/12/12 13:24:40 [sample-tekton-pipelines-push-event] Validation FAIL (error Webhook request has unsupported Content-Type "" validating payload)
```
at
```
payload, err := github.ValidatePayload(request, foundSecret.Data["secretToken"])
```
I'll look at the eventlistener if it add the `content-type`.

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/experimental/pull/409
