### ISSUE TITLE
Update release pipeline for our Triggers release

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#349]
Currently we have plenty of mentions of `sink`, likely this can simply be replaced with `interceptor`.

Under this task update the release pipeline (see the `tekton` folder), do a trial and run/dummy release and celebrate.

**Comment by dibbles** [comment]
https://github.com/tektoncd/experimental/pull/367

**Comment by a-roberts** [comment]
We reckon this is done, code is merged, just need to test before closing to verify
