### ISSUE TITLE
Pipelineruns are not created when repo is in an org 

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#375]
*Expectation:*

Repository in a github enterprise org should trigger a pipeline via a webhook.

*Actual behaviour:*

The interceptor errors with

```
2019/11/29 14:15:45 [main-tekton-pipelines-push-event] Failed to add branch to payload processing Github event ID: bb942e3a-12b2-11ea-8de2-064a7288b3e0. Error: json: cannot unmarshal string into Go struct field Repository.organization of type github.Organization
```

Reason:

It looks like a different api is being used to handle the payload of the github events.  In 0.2.1 it was 

`"gopkg.in/go-playground/webhooks.v3/github"`

In master, the interceptor uses

`"github.com/google/go-github/github"`

We could either move back to the previous API and unmarshal the payloads as in the old sink.go or find the correct structure into which to unmarshall on the go-github api.

NOTE:  There is a difference in webhook push event payloads for ORG v OWNER repos, ensure you test both by creating your own org.

**Comment by a-roberts** [comment]
Merged so closing
