### ISSUE TITLE
Modify example pipelines to use resourceSpec with Triggers

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#376]
See https://github.com/tektoncd/triggers/issues/244

What we have at https://github.com/pipeline-hotel/example-pipelines/tree/master/triggers-resources/config is very likely to have the same problem mentioned above, so under this issue modify the example trigger pipelines to use resourceSpec in the Pipeline definition for the buildah and simple-pipeline TriggerTemplates.

**Comment by dibbles** [comment]
also while there.... worth modifying bindings to use:

```
  - name: docker-tag
    value: $(body.repository.name):$(body.webhooks-tekton-image-tag)
```

which should in effect mean we have examples that work with git pushes of git tags
