### ISSUE TITLE
Octant Plugin: Create New Tab for Tekton in Dashboard Instead of Putting Information Under CRD Tab 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/experimental#391]
Currently, the Octant plugin for Tekton links data for Tekton to the resources under the Custom Resources tab:

![image](https://user-images.githubusercontent.com/34258252/70530965-fa928b00-1b21-11ea-93ad-a4bcc1a3c1cf.png)

It would be nice to have this information shown under a tab specifically devoted to Tekton so that there is no confusion over how to find the information in the Octant dashboard.

**Comment by mnuttall** [comment]
Hi @danielhelfand does this issue belong in https://github.com/vmware-tanzu/octant? We don't currently do any Octant-related work in this repository.

**Comment by mnuttall** [comment]
@danielhelfand  @ImJasonH does this relate to the octant-plugin? (I wasn't aware of it but just saw https://github.com/tektoncd/experimental/pull/361.)

**Comment by ImJasonH** [comment]
Yeah we should do this. It looks like the plugin system allows plugins to register navigation (sidebar) components ([sample](https://github.com/vmware-tanzu/octant/blob/6303f7e7584399a739af52b5e9b594cb4d530244/cmd/octant-sample-plugin/main.go#L148-L168)). I'm not sure if it also allows plugins to hide CRD types from the CRD navigation section, but that's probably less important.

**Comment by danielhelfand** [comment]
@ImJasonH As you say, I think it's not a big deal to hide CRDS, but a space truly focused on Tekton within the dashboard I think would be really great. 

I can take a shot as this unless you already have some thoughts around this.

**Comment by ImJasonH** [comment]
@danielhelfand Yeah that makes sense. If you want to do it that's fine, I probably won't have time to immediately, and it'd be great to have others involved in the Octant plugin. :muscle:
