### ISSUE TITLE
Duplicate config YAML files are a pain

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#394]
# Expected Behavior
As a developer, I expect it to be easy to update the webhook release and track changes to the pieces of the release.

# Actual Behavior
Right now it is confusing to update the release, because there are 5 files that are mostly duplicates of one another:
1. [`extension-deployment.yaml`](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/extension-deployment.yaml)
2. [`openshift-tekton-webhooks-extension-release.yaml`](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/openshift/openshift-tekton-webhooks-extension-release.yaml)
3. [`openshift-tekton-webhooks-extension.yaml`](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/latest/openshift-tekton-webhooks-extension.yaml)
4. [`gcr-tekton-webhooks-extension.yaml`](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/latest/gcr-tekton-webhooks-extension.yaml)
5. [`openshift-tekton-webhook-extension-development.yaml`](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/config/openshift-development/openshift-tekton-webhooks-extension-development.yaml)

This makes it difficult to track changes to the release, and makes it easy to create inconsistencies between the YAML files. Ideally, there should be no duplicate release YAML code in the repo. Plus, it would be helpful if each k8s object in the release could have its own file (ex: https://github.com/tektoncd/pipeline/tree/master/config).

**Comment by mnuttall** [comment]
I have a plan for this! We can use https://github.com/kubernetes-sigs/kustomize to remove the duplication.

**Comment by a-roberts** [comment]
Merged so closing 🎉 

Linking here to the dashboard issue @ncskier made too: https://github.com/tektoncd/dashboard/issues/822

Note I had to upgrade my kubectl version (I think the minimum is 1.16) using brew to be able to do the `kubectl -k` commands.
