### ISSUE TITLE
Deleting the pipelinerun causes pull request status to be successful

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#395]
# Expected Behavior

When a pull request is created, I would expect the status of the pull request to be "failed" or "error", if I delete the pipelinerun whilst it is running.

# Actual Behavior

The status is success and the table of pipelineruns simply shows the table headers and no pipelineruns.

# Steps to Reproduce the Problem

1. create webhook
2. create pull request to repo
3. when pipelinerun and monitor task are running, delete the pipelinerun

# Additional Info

**Comment by a-roberts** [comment]
Reproduced oddities here, deleted the running PipelineRun for my pull request as mentioned in the recreate.

I noticed a comment was made saying the PipelineRun had failed, then it went back to pending, and then I commented with just the table headers, so here's what I end up with:

![image](https://user-images.githubusercontent.com/12814972/70702809-cc01e500-1cc6-11ea-89b8-552690233c74.png)

![image](https://user-images.githubusercontent.com/12814972/70702848-e1770f00-1cc6-11ea-8534-4a5966203222.png)

**Comment by a-roberts** [comment]
One way I think we can fix this is with a simple else for the if:

`if len(api_response["items"]) > 0:`

We can set a flag and then only write the comment (the table) in this scenario. 

Unfortunately to complete my testing of this we really want https://github.com/tektoncd/experimental/issues/404 fixed, which I found while implementing this. For this code change we've agreed on using `Error` for the status and I propose `No PipelineRuns found!` for the description.

**Comment by a-roberts** [comment]
So far I have this

![image](https://user-images.githubusercontent.com/12814972/70816767-1b7c0a00-1dc8-11ea-9e70-85f1d39c21a3.png)

which involves a customisable missing comment (I've got a German translation example too that compliments the others)

Testing the scenario now where the monitor task is looking at multiple PipelineRuns and only the one is deleted, so we should have a table with 

Missing
Success

I believe this involves setting up multiple pipelines on the same repo so they will have the same trigger ID.

**Comment by a-roberts** [comment]
So far I have this

![image](https://user-images.githubusercontent.com/12814972/70816767-1b7c0a00-1dc8-11ea-9e70-85f1d39c21a3.png)

which involves a customisable missing comment (I've got a German translation example too that compliments the others)

Testing the scenario now where the monitor task is looking at multiple PipelineRuns and only the one is deleted, so we should have a table with 

Missing
Success

I believe this involves setting up multiple pipelines on the same repo so they will have the same trigger ID.

**Comment by a-roberts** [comment]
PR at https://github.com/tektoncd/experimental/pull/408, seeing some funky test failures atm

**Comment by a-roberts** [comment]
Fix is merged so closing
