### ISSUE TITLE
Stop using Knative for webhooks 

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#40]
The initial webhooks implementation used the Knative and the Knative GitHub Event Source to:
- Create and delete GitHub webhooks 
- Expose an external endpoint via ksvc/Ingress for the GitHub webhooks to be delivered to 
- Deliver webhook payloads to the webhooks 'sink' code for processing

The Knative dependency resulted in 'webhooks' being implemented as a dashboard extension rather than as core dashboard capability. It also complicates the installation process. Remove our Knative dependency by:
- Extending the Dashboard install operator to include an Ingress endpoint for webhook delivery
- Use Go libraries directly to register and delete webhooks
- See https://github.com/tektoncd/experimental/issues/39: webhooks should cause PipelineRun creation through the Tekton Events code: can this function in the absence of Knative? Find out !

See also https://github.com/tektoncd/dashboard/issues/212 - we need to know how we're going to handle Ingress as part of this work.

**Comment by chhsia0** [comment]
I was wondering that, maybe we could consider [Argo events](https://github.com/argoproj/argo-events) as a light-weight alternative to knative eventing? This would also help with GitLab support.

**Comment by mnuttall** [comment]
See also https://github.com/tektoncd/experimental/issues/209

**Comment by AlanGreene** [comment]
The webhooks extension is deprecated, closing stale issues.

/close
