### ISSUE TITLE
Re-check RedHat OpenShift registry on 4.2 and update docs

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#416]
Our document `NotesOnOpenShiftInstallations.md` in the section [Pushing to the OpenShift registry using webhooks](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/NotesOnOpenShiftInstallations.md#pushing-to-the-openshift-registry-using-webhooks) specifies a registry location of 

```image-registry.openshift-image-registry.svc:5000/kabanero```

 but in https://github.com/tektoncd/experimental/issues/305 @a-roberts wrote, 
> `docker-registry.default.svc:5000/kabanero` is what should be used (note the lack of trailing slash), otherwise the buildah pipeline for example fails (tries to use two slashes). 

It looks as though our docs need a slight update to reflect the different repository URLs that need to be used for OpenShift 3.11 and 4.2.

**Comment by akihikokuroda** [comment]
The 
```
image-registry.openshift-image-registry.svc:5000/kabanero
```
is the correct URL for OpenShift 4.2.  The doc is correct for 4.2.  Should we add the URL for 3.11 
```
docker-registry.default.svc:5000/kabanero
``` 
in the doc?

**Comment by a-roberts** [comment]
Yeah I would, we're still going to have OpenShift 3.11 users 😄

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/experimental/pull/428

**Comment by a-roberts** [comment]
Merged this so closing, thanks Aki
