### ISSUE TITLE
Webhooks support for Gitlab

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#42]
Currently we can only create webhooks for GitHub. GitLab is a widely used alternative that we should support. 

Note that Epic https://github.com/tektoncd/experimental/issues/40 would remove our use of the Knative GitHub Event Source. The implementation work under this epic needs to take that done, or planned, under 40 into account.

**Comment by a-roberts** [comment]
Oops - assigned @dibbles to this one 😄 an update on this is that the prototype issue is done and works well, merged it this morning https://github.com/tektoncd/experimental/issues/58

**Comment by dibbles** [comment]
I believe this can be closed (so I'm closing it) - I think I have fully implemented everything required
