### ISSUE TITLE
Could not find the required trigger template or trigger bindings in namespace

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#429]
Original issue: https://github.com/tektoncd/triggers/issues/349
This issue was originally created by @JCzz in the Tekton Triggers repo. I moved the issue here because it seems to be primarily about the Webhooks Extension.

---

Creating Webhook

I am trying to create a webhook in the Tekton Dashboard.

I have successfully done:
build-docker-image-from-git-source:
https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs

And Triggers example:
https://github.com/tektoncd/triggers/tree/v0.1.0/examples

Now I am trying to create a github Webhook:
https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md

Then I get the following Error:
`Failed to create webhook, error returned was : Could not find the required trigger template or trigger bindings in namespace: tekton-pipelines. Expected to find: tutorial-pipeline-template, tutorial-pipeline-push-binding and tutorial-pipeline-pullrequest-binding`

From these Webhook Settings:

```
Name: tektonbuild-github-webhook
Repository URL: https://github.com/githubuser/tektonbuild.git
Access Token: xxxxx

Namespace: default
Pipeline: tutorial-pipeline
Service Account: tutorial-service
Docker Registry: gcr.io/<project>/imagetobuild
```

Question / problem:

1. 
From the error, I can read that Triggers has to be in the tekton-pipelines namespace with specific naming. But I don't understand this as the "Triggers example" works in the default namespace?

The error comes when I press the button "Create"

I can see in the documentation says " Pipeline definitions must be imported along with TriggerBindings and TriggerTemplates." Does that mean I have to "kubectl apply" TriggerBinding & TriggerTemplates , but not the PipelineRun, TaskRuns, Task and PipelineResources?

2.
In the dashboard When setting up Target pipeline:
I know I am just missing something, but why do we need to set the pipeline when creating a webhook and not the Eventlistener?

**Comment by ncskier** [comment]
> Then I get the following Error:
`Failed to create webhook, error returned was : Could not find the required trigger template or trigger bindings in namespace: tekton-pipelines. Expected to find: tutorial-pipeline-template, tutorial-pipeline-push-binding and tutorial-pipeline-pullrequest-binding`

I think that this error is occurring because you do not have the required TriggerTemplate and TriggerBinding in the `tekton-pipelines` namespace. I assume that you are trying to create a Webhook to run the `tutorial-pipeline` Pipeline. To correctly set up your webhook, you must import your TriggerTemplate named `tutorial-pipeline-template` and TriggerBindings named `tutorial-pipeline-push-binding` and `tutorial-pipeline-pullrequest-binding` into the `tekton-pipelines` namespace (the namespace the Webhook Extension was installed in).

The Webhooks Extension uses one EventListener in the `tekton-pipelines` namespace to manage all webhooks. So, the Tekton Triggers resources (TriggerTemplate and TriggerBinding) must be created in the same namespace (`tekton-pipelines`). On the other hand, the Webhook creates a PipelineRun in the namespace of your choice, we'll call the namespace `webhook-ns`. So, Tekton Pipeline resources (Pipeline, Task) must be created in the same namespace (`webhook-ns`). All of this is explained in more detail in this [Webhook Extension Architecture Doc](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/Architecture.md#initial-setup-overview).

You might have noticed that in my explanation above, the Triggers resources (TriggerTemplate and TriggerBinding) have to follow a strict naming convention. The reasoning behind that is explained in this [Webhooks Extension Limitations Doc](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/Limitations.md#trigger-template--trigger-bindings).

**Comment by ncskier** [comment]
Hi @JCzz what version of the Webhooks Extension have you installed? It's strange that Ingress isn't in the ClusterRole; that might be a bug with the version you've installed; thanks for finding this!

Also, I noticed that you added a rule for the `networking.k8s.io` apiGroup, but your error message says that `ingresses` are in the `extensions` apiGroup. If you add the rule for the `extensions` apiGroup, does that solve the problem?

**Comment by JCzz** [comment]
Hi @ncskier 

Just used the last days to get a stronger understanding of RBAC - I thought :-) I simply can not get it to work. 

Let me try to describe my environment:

I installed following this "[Installing Official Release](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/InstallReleaseBuild.md)"

Using:
```
curl -L https://github.com/tektoncd/dashboard/releases/latest/download/webhooks-extension_release.yaml \
| sed -e 's/IPADDRESS/YOUR_IP_ADDRESS/g' \
| kubectl apply -f - 
```


I am running on Google Kubernetes Engine:
```
kubectl version                                                                               christian@Christisans-MacBook-Pro
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl get pods --namespace tekton-pipelines --watch                                         christian@Christisans-MacBook-Pro
NAME                                                   READY   STATUS    RESTARTS   AGE
tekton-dashboard-86c6fb964b-ln7ll                      1/1     Running   0          10d
tekton-pipelines-controller-5f7f67dd8c-qw8hn           1/1     Running   0          14d
tekton-pipelines-webhook-54bbb46d4-c6x42               1/1     Running   0          9d
tekton-triggers-controller-6d8fd9596b-z9nfs            1/1     Running   0          8d
tekton-triggers-webhook-5f8d569d5f-cwb6n               1/1     Running   0          8d
tekton-webhooks-extension-validator-6f8c9987b7-mmd7h   1/1     Running   0          5d23h
webhooks-extension-7954fd5969-6v72n                    1/1     Running   0          5d23h
```

# Lastly
I tried to give privileges like the following

Role:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tekton-pipelines
  name: tekton-awear-role
rules:
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - '*'
```

RoleBinding:

```
--clusterrole=testuseraccess

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-awear-rolebinding
  namespace: tekton-pipelines
subjects:
- kind: Group
  name: system:serviceaccount:tekton-pipelines:tekton-webhooks-extension
  apiGroup: "" 
roleRef:
  kind: Role
  name: tekton-awear-role
  apiGroup: rbac.authorization.k8s.io
```

Thanks for any help

**Comment by JCzz** [comment]
It worked: ServiceAccount actually worked not using Groups...

**Comment by ncskier** [comment]
I'm glad you got it working @JCzz! 👍 Can I close out this issue?

**Comment by JCzz** [comment]
Hi @ncskier 
Yes, please close this one - and I think you should elevate the privileges for `system:serviceaccount:tekton-pipelines:tekton-webhooks-extension` to include "ingresses" in apiGroup "extensions".

Thanks for you help

**Comment by ncskier** [comment]
No problem! Also, if you aren't installing on OpenShift, then as far as I can tell the ingress should be included in the Role (for OpenShift, routes should be used instead of ingress): https://github.com/tektoncd/experimental/blob/master/webhooks-extension/overlays/plainkube-all/role-patch-json.yaml#L5
