### ISSUE TITLE
Assess the move to Triggers 0.2 (webhooks)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/experimental#431]
As an end user I expect to be able to use the Tekton Dashboard with Triggers 0.2. When using the webhooks extension there's a fundamental flaw with our architecture too - a user can't create more than eight webhooks or they'll get an admission webhook timeout error (more details at tektoncd/triggers#356)

Related dashboard issue https://github.com/tektoncd/dashboard/issues/918

**Comment by a-roberts** [comment]
I'm going to binary chop checkout/build the Triggers codebase to see when the performance really improved for the EventListener, there are catastrophic failures for the dashboard atm https://github.com/tektoncd/dashboard/issues/918#issuecomment-576219224 😄

**Comment by a-roberts** [comment]
I pinged @ncskier about this, Brandon mentioned https://github.com/tektoncd/experimental/blob/1ccc14ed15c4b8640f0cdba95886b2db60bd0d73/webhooks-extension/pkg/endpoints/webhook.go#L152 

We do use `params`, but now in Triggers 0.2 they don't exist - we have to create a separate TriggerBinding resource for them. There should be an issue floating around somewhere for embedding the TriggerBinding spec in the EventListener, but it hasn’t been implemented yet (this is missing in the Triggers release notes atm)

**Comment by ncskier** [comment]
Another change to note (discussed in the Triggers call today) is that the gjson syntax will no longer be supported; instead we must use JSONPath syntax:
> gjson syntax for TriggerBindings was removed in favor of JSONPath.

This is not a problem for the Webhooks Extension itself, but anyone using the Webhooks Extension will have to update their TriggerBindings to use the JSONPath syntax.

**Comment by a-roberts** [comment]
Assessment done for what we can do so far, closing
