### ISSUE TITLE
Improve Amazon EKS installation for webhooks extension

### ISSUE THREAD

**Issue by JCzz** [tektoncd/experimental#432]
You have a note for "Notes for Amazon EKS" in this [Getting started with the Tekton Dashboard Webhooks Extension](https://github.com/tektoncd/experimental/blob/2d2d8e2b6010c69903dc6af2c69e8e3f095240bb/webhooks-extension/docs/GettingStarted.md)

Even I dont quite understand where you should edit "el-tekton-webhooks-eventlistener",
do you have any descriptions on how to get an external Loadbalancer up for Google Kubernetes Engine ?

I would like to do what you do for "Amazon EKS" - to be abl eto change for a LoadBalancer

**Comment by a-roberts** [comment]
Yeah, it'd be nice if we had our own Amazon EKS file as an overlay file you can just kubectl apply upfront (so similar to what we do for OpenShift at the moment), I'm gonna rename this issue accordingly so someone could easily run with it and know what to do

I think in your case it's going to be a case of creating a webhook initially (this creates the EventListener), then doing the `kubectl edit ingress el-tekton-webhooks-eventlistener` command and following steps, we should certainly make this obvious and improve the experience

@akihikokuroda FYI

I haven't used an External LoadBalancer for GKE so curious too, I'm hoping that's under the platform documentation. We don't really have a testing story for webhooks on GKE so your mileage may vary 🤞

**Comment by JCzz** [comment]
Hi @a-roberts 

Thanks, I tried to edit but got error: ingresses.extensions "el-tekton-webhooks-eventlistener" is invalid:

```
kubectl edit ingress el-tekton-webhooks-eventlistener --namespace=tekton-pipelines            christian@Christisans-MacBook-Pro
error: ingresses.extensions "el-tekton-webhooks-eventlistener" is invalid
A copy of your changes has been stored to "/var/folders/3p/8z23nlbs20qf291vlhjy1l0h0000gn/T/kubectl-edit-1kokn.yaml"
error: Edit cancelled, no valid changes were saved.
```

el-tekton-webhooks-eventlistener:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  creationTimestamp: "2020-01-20T17:12:47Z"
  generation: 1
  name: el-tekton-webhooks-eventlistener
  namespace: tekton-pipelines
  resourceVersion: "26157646"
  selfLink: /apis/extensions/v1beta1/namespaces/tekton-pipelines/ingresses/el-tekton-webhooks-eventlistener
  uid: 148e6bdc-3ba8-11ea-baa1-42010a8401f0
spec:
  rules:
  - host: listener.mydomain.dev
    http:
      paths:
      - backend:
          serviceName: el-tekton-webhooks-eventlistener
          servicePort: 8080
status:
  loadBalancer: {}
```

**Comment by akihikokuroda** [comment]
The service above is not the one should be changed.  It 's the service for the validator.  The service for the listener is created at the runtime so it is not exposed in a yaml file.

**Comment by akihikokuroda** [comment]
I revisited the "Notes for Amazon EKS", The ingress doesn't need the "rule-> host",  the host line can be removed at the same time the annotations are added.
