### ISSUE TITLE
Update Uninstall.md to include the route deletion

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/experimental#441]
The route remains after uninstall of the webhook extentions in the OpenShift environment.  The Uninstall.md should  include the instructions how to delete the resources created during the runtime including the route resource.

https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/Uninstall.md

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/444, also includes ingress

**Comment by a-roberts** [comment]
Merged so closing
