### ISSUE TITLE
Monitor marks pull request as success when no pipelineruns have run

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#442]
# Expected Behavior

A pull request should not be marked as successful when there are no pipelineruns for the monitor to watch.

# Actual Behavior

The pull request was marked as successful with a table of just headers and no pipelineruns.

# Steps to Reproduce the Problem

The below is a bit of a guess - I found this whilst doing development work where the eventlistener failed to trigger the pullrequest trigger but triggered the monitor.  I would guess this is the equivalent of:

1. Make your triggertemplate and binding in such a way that the eventlistener cannot create the pipelinerun

# Additional Info

**Comment by a-roberts** [comment]
This could be an easy one (defaulting the status) so I'm going to work on this with our currently supported monitor task set up (so independently from the work @dibbles is doing to upgrade our Triggers version)

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/73276809-2c020b80-41e1-11ea-8428-038feeae8ef6.png)

it works but reminds me of Ned Flanders (feels like I'm wearing...nothing at all!)

**Comment by a-roberts** [comment]
PR https://github.com/tektoncd/experimental/pull/443

**Comment by a-roberts** [comment]
Merged so closing
