### ISSUE TITLE
Unify Experimental Eventing 

### ISSUE THREAD

**Issue by vtereso** [tektoncd/experimental#46]
As both of the experimental projects address the same core problem, triggering `pipelineRun`s, it makes sense to coalesce into one code base. 

In the current form of the `webhooks-extension` code, RESTful endpoints use internal representations/structs and config-maps to stand as a (less than ideal) `pipelineRun` templating solution. Although heavily constrained, for the use case it does generate `pipelineResource`s at event time as well as the corresponding `pipelineRun`. 

The `tekton-listener` code/subrepo solely addresses triggering (not templating) through K8s CRDs and controllers. When an `eventBinding` custom resource is created, the controller creates all the `pipelineResource`s specified in the spec and then create a `tektonListener`, which has a pod waiting for events. When an event in received, a `pipelineRun` is created as specified in the `tektonListener`'s `pipelineRunSpec`. 

The `tekton-listener` abstraction is an improvement over the `webhooks-extension` approach since CRDs are used rather than internal structures and config-maps. Furthermore, CRD controllers provide a more K8s native approach (which is in-line with Tekton) than the `webhooks-extension` server approach. However, the `tekton-listener` eventing mechanism does not have any templating support. So, we cannot create a `pipelineResource` using event  data. 

At the moment, the `tekton-listener` code cannot be used by the `webhooks-extension` because the `tekton-listener` lacks templating for `pipelineRun`s/`pipelineResource`s. In order to merge both projects, we need to discuss the situation and come to some solution.

**Comment by a-roberts** [comment]
@vtereso @ncskier am I right in thinking this is being worked by yourself as part of the whole `triggers` repository? 

If so can you update this issue's status accordingly please (even if it's just to assign yourself and move to in progress)? 

I'm thinking that's the case but it's lingering in the backlog for anyone else to pick up rn

**Comment by ncskier** [comment]
Update:
Most of the discussion about unifying the Experimental eventing is documented in issue https://github.com/tektoncd/pipeline/issues/315. The unified proposal/design (https://docs.google.com/document/d/1fngeNn3kGD4P_FTZjAnfERcEajS7zQhSEUaN7BYIlTw) is now beginning its implementation phase in the [triggers repo](https://github.com/tektoncd/triggers). 

Progress can be tracked on the trigger repo's [ZenHub board](https://github.com/tektoncd/triggers#workspaces/triggers-5d0ebce343e42a09a0a4a826/board?repos=193171705), and any major developments (such as code that can be used by the dashboard webhooks-extension) will be documented under this issue.
