### ISSUE TITLE
Add 'Repository' and 'Branch' filters to PipelineRuns

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#47]
This issue is part of `experimental` epic #37 but concerns development changes in `dashboard`. The webhooks extension needs to be able to filter pipeline runs by repository and branch: it makes sense to surface this capability to dashboard users. 

Under Dashboard > PipelineRuns, users should be able to filter the pipeline runs shown by 'git repository' and 'branch'. These can be passed as query params to the /pipelineruns REST API. We should apply labels to pipeline runs so as to be able to filter by these labels when obtaining pipeline runs via the Go client.

**Comment by vtereso** [comment]
IIUC, a pipelineRun is related to a branch/repo through an assumed GitResource (as specified [here](https://github.com/tektoncd/pipeline/blob/ffbb67959dec0abb0f07b1d456398a99531d89f8/pkg/apis/pipeline/v1alpha1/git_resource.go#L46)). I will add labels to runs created through the dashboard should the resource exist.

**Comment by dibbles** [comment]
I'm not sure this approach would fulfill what we are attempting to achieve, unless I have misunderstood things in the PR (see further notes on PR) : https://github.com/tektoncd/dashboard/pull/279

**Comment by kimholmes** [comment]
Working on this user flow. Would love feedback:

**Default state:**
![TektonFilter1](https://user-images.githubusercontent.com/21316329/63121298-1326d600-bf72-11e9-8846-b5bb06a8651e.png)

**Hover state:**
![TektonFilter2](https://user-images.githubusercontent.com/21316329/63121318-1f129800-bf72-11e9-8a67-c185a454ad96.png)

**Click state:**
![TektonFilter3](https://user-images.githubusercontent.com/21316329/63121341-2df94a80-bf72-11e9-8888-6ef62c81cd44.jpg)

**Typing state. User can press enter or select from the dropdown:**
![TektonFilter4](https://user-images.githubusercontent.com/21316329/63121556-bd066280-bf72-11e9-8a5a-ebd8fd7dd85e.jpg)

**Filter added:**
![TektonFilter5](https://user-images.githubusercontent.com/21316329/63121607-ddceb800-bf72-11e9-9147-2d12ad1c8791.jpg)
