### ISSUE TITLE
Triggers API Group change in Triggers v0.4.0

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#472]
Issue https://github.com/tektoncd/triggers/issues/332 proposes to change the API Group for Triggers resources. This will break the Webhooks-Extension.

cc @dibbles 
cc @a-roberts

**Comment by ncskier** [comment]
This Triggers issue was moved back to the v0.4.0 release, because it will break the upgrade process to the next version of Triggers. I think that all Triggers resources will probably have to be deleted and then re-created.

**Comment by a-roberts** [comment]
I handled this as part of another issue and @ncskier has been working with Rodolfo on a webhook migration strategy, nothing to do here now so closing
