### ISSUE TITLE
Upgrade webhooks extension to work with Pipelines 0.11.x

### ISSUE THREAD

**Issue by anneqm** [tektoncd/experimental#476]
Test with Tekton pipelines 0.11 when it becomes available and address any needed changes in the webhooks extension. Note change to v1alpha2.

# Additional Info

**Comment by a-roberts** [comment]
Haven't noticed any need to change anything yet despite what's in our Gopkg toml

**Comment by a-roberts** [comment]
Closing as nothing to do or I've done it
