### ISSUE TITLE
Using CronJobs to automatically clean up completed Runs

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/experimental#479]
# Expected Behavior

Create a new tool that uses CronJob objects to schedule the cleanup of completed TaskRuns and PipelineRuns.

This could have use in our own dogfooding and also provide the community with help managing their own completed runs.

In [a prior PR](https://github.com/tektoncd/pipeline/pull/1486) we explored the idea of using a TTL on runs and leveraging the Kubernetes TTL Controller to help clean them up. During that review process a user suggested CronJobs as an alternative to baking this TTL support directly into the Tekton Pipelines controller.

# Actual Behavior

We don't currently have any way to automatically clean up completed TaskRuns and PipelineRuns but we definitely hear feedback that some kind of tooling or guidance would be very useful.

**Comment by assertion** [comment]
We have the same requirement to delete the completed resources automatically. ( Status may need to be considered, for example Failed PipelineRun should be deleted after a longer time than the Succeeded PipelineRun).

(Actually, now we delete these resources by our apiServer above Tekton through monioring the pipelineRun related events and when it's finished, we'll delete the succeeded pipelineRuns after a short time, and delete the failed pipelineRuns after a longer time ).

**Comment by jlpettersson** [comment]
I'll have a look into this.

/assign

**Comment by k** [comment]
@jlpettersson any update on this? Right now I have a pretty janky kubectl command to delete old pipeline runs lol

**Comment by jlpettersson** [comment]
> @jlpettersson any update on this? Right now I have a pretty janky kubectl command to delete old pipeline runs lol

It should not be much more job. Give me a few days.

**Comment by mattmoor** [comment]
> In a prior PR we explored the idea of using a TTL on runs and leveraging the Kubernetes TTL Controller to help clean them up. During that review process a user suggested CronJobs as an alternative to baking this TTL support directly into the Tekton Pipelines controller.

🤔  Seems like following the idioms established for K8s Jobs would be somewhat prudent.  If we were to establish a "ttl" duck type (e.g. for how this is embedded into specs) combined with the use of a `Succeeded` condition, then you could write a shareable meta controller that handles this for all types.

cc @n3wscott (this would benefit from the ideas in our last Kubecon talk)

**Comment by sbwsg** [comment]
@afrittoli has implemented this kind of pruning behaviour in our dogfooding cluster now 🎉 🎉 .  That work could help inform this issue.  Here's the PR where his changes were added: https://github.com/tektoncd/experimental/issues/479

**Comment by sbwsg** [comment]
I'm keeping this issue open as it's a feature area that is still seeing semi-regular community requests.

/lifecycle frozen

**Comment by psschwei** [comment]
@sbwsg you're thinking that this would just be a sample cronjob (and related resources) that users could apply to their own clusters, correct (similar to what @afrittoli did on the dogfooding cluster)? Perhaps under the `examples/` directory. 

Assuming that's the case...
/assign

**Comment by sbwsg** [comment]
Great!  Documenting this as part of Pipelines would also be really useful.

**Comment by jlpettersson** [comment]
This CronJob was shared by Tekton twitter account: https://gist.github.com/ctron/4764c0c4c4ea0b22353f2a23941928ad
