### ISSUE TITLE
View list of branches for a webhook

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#48]
Further to #47 and as per the .pdf sketch linked in #37, clicking on a webhook name in the list of webhooks should take the user to a list of branches in the associated git repository. This will need additional support from the REST API to retrieve this list - we might as well get the list of branches from git, rather than by scraping them from all the pipelineruns we might have. 

(There's the possibility of some branches existing but having no builds, and of builds existing whose branches have been deleted. That could be a problem but we're deferring it for now.)

**Comment by mii-w** [comment]
First take from referencing Alan's and Duane's screens
<img width="615" alt="Screen Shot 2019-09-20 at 11 33 04 AM" src="https://user-images.githubusercontent.com/51759906/65339656-8c7d9e00-db9a-11e9-9b75-e4b553d9b702.png">

**Comment by mii-w** [comment]
![Screen Shot 2019-10-02 at 12 52 01 PM](https://user-images.githubusercontent.com/51759906/66064495-7b764a80-e513-11e9-94a3-de475f55e33f.png)
![Screen Shot 2019-10-02 at 12 52 09 PM](https://user-images.githubusercontent.com/51759906/66064502-7e713b00-e513-11e9-9ef6-d6078c62861f.png)

**Comment by mii-w** [comment]
Clickable wireframe Prototype:
https://ibm.invisionapp.com/share/PCNZBZYNKQF

**Comment by carlos-logro** [comment]
first pass has been merged, unassigning but not closing due to new designs 
/unassign
