### ISSUE TITLE
View webhook settings in 'details' panel

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#51]

**Comment by kimholmes** [comment]
@mnuttall Please provide a description.

**Comment by akihikokuroda** [comment]
From API, the user can set the following items in the webhook configuration.  I assume that the UI should have the same.

Mandatory items:
```
        Name
        Namespace
        GitRepositoryURL 
        AccessTokenRef 
	Pipeline
```
Optional items:
```
        ServiceAccount 
        DockerRegistry 
	HelmSecret        
        ReleaseName 
```

**Comment by mi-wang** [comment]
I put the optional items under a dropdown box label 'Additional Details'
![Screen Shot 2019-07-30 at 1 00 10 PM](https://user-images.githubusercontent.com/51759906/62149585-10698700-b2ca-11e9-80a0-1d73a69c93c4.png)

**Comment by ncskier** [comment]
@mnuttall This issue doesn't have a description, and I think there's some confusion about what the issue is actually specifying (at least I'm slightly confused 😅 ).

I thought that this issue was about creating paneling for this page in the Webhooks Extension:
![Screen Shot 2019-07-31 at 8 49 29 AM](https://user-images.githubusercontent.com/16961496/62213166-52e59f00-b370-11e9-8f38-3c8e1b397d46.png)
(pages 7 & 8) of @dibbles [Extension.pdf](https://github.com/tektoncd/experimental/files/3451887/Extension.pdf). Is that correct?

**Comment by dibbles** [comment]
Yes ... although some of what is on those pages might be wishful thinking on my part .... mostly the paramters table as we haven't really put any thought into setting/overriding parameters on a pipeline - or if we have a use case for that the moment.

**Comment by mii-w** [comment]
First take
<img width="617" alt="Screen Shot 2019-09-20 at 11 32 56 AM" src="https://user-images.githubusercontent.com/51759906/65339819-d9fa0b00-db9a-11e9-8526-801eb7f3942e.png">

**Comment by kimholmes** [comment]
Notes. Please provide feedback:
![webhooksDetail_forPublic](https://user-images.githubusercontent.com/21316329/65788533-417b0200-e129-11e9-891f-831e908752a6.png)

**Comment by mii-w** [comment]
![Screen Shot 2019-10-01 at 10 11 19 AM](https://user-images.githubusercontent.com/51759906/65970089-de90b000-e433-11e9-9942-6b3846e66146.png)
![Screen Shot 2019-10-01 at 10 11 26 AM](https://user-images.githubusercontent.com/51759906/65970092-e0f30a00-e433-11e9-8ae5-e9fbe7d3b093.png)

**Comment by mii-w** [comment]
![Screen Shot 2019-10-02 at 12 58 15 PM](https://user-images.githubusercontent.com/51759906/66064922-5e8e4700-e514-11e9-8aec-c893ebb47fed.png)
![Screen Shot 2019-10-02 at 12 58 39 PM](https://user-images.githubusercontent.com/51759906/66064924-60580a80-e514-11e9-8aa6-a6a1ad1dbd0e.png)

**Comment by mii-w** [comment]
Latest Clickable prototype!
https://ibm.invisionapp.com/share/PCNZBZYNKQF

Feedback Appreciated!
