### ISSUE TITLE
Design for access token management

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#53]
As per Epic #38, 
> The 'first pass' at panelling for webhook management allows for access tokens to be created and deleted. We need a separate 'access token management' page where existing tokens can be presented in tabular form, as well as created and deleted. (Edit is not required.)

> Consider whether users creating webhooks can be linked to and from a unified access token management dialog when creating one in the process of creating a webhook.

Key issues to resolve: 
- What's the navigation path to the access token management page?
- Given the restrictions imposed by the 'extension' architecture, can the 'create webhook' panelling be refactored so as to pass 'create access token' to a unified 'create' panel? Or is the current 'pop up' panel ok as it is?

**Comment by mi-wang** [comment]
Creation Flow for Secrets: (first pass)
![1Create Secret](https://user-images.githubusercontent.com/51759906/61238794-6acfe880-a70b-11e9-8f94-270c26854bf4.png)
![2Secret Credentials](https://user-images.githubusercontent.com/51759906/61238796-6acfe880-a70b-11e9-9715-02a70a778792.png)
![3Connectivity](https://user-images.githubusercontent.com/51759906/61238798-6acfe880-a70b-11e9-8e9d-62b38818df08.png)
![4successdialogue](https://user-images.githubusercontent.com/51759906/61238800-6b687f00-a70b-11e9-85b9-deaa767a2bf2.png)

working on linking webhooks

**Comment by mi-wang** [comment]
My mistake on mixing up Secrets and Access Token Management!
Here is an update:

![1Access Token](https://user-images.githubusercontent.com/51759906/61380581-9ff94980-a877-11e9-9a12-1b068ef71fdf.png)
![2Access Token Import](https://user-images.githubusercontent.com/51759906/61380582-9ff94980-a877-11e9-8fa0-272be6a0ca1e.png)
![success](https://user-images.githubusercontent.com/51759906/61380583-9ff94980-a877-11e9-876b-702605f9b044.png)

Invision link: https://ibm.invisionapp.com/share/9QNZ3R7SC4F

**Comment by mi-wang** [comment]
Thanks for feedback! I made the changes :)

Updated Invision Link:
https://ibm.invisionapp.com/share/UBNZ3TAXAY2

![1 secrets](https://user-images.githubusercontent.com/51759906/61406083-2aa66c80-a8a9-11e9-8ab8-9d8bb28e9fac.png)
![1 UserPass](https://user-images.githubusercontent.com/51759906/61406085-2aa66c80-a8a9-11e9-828f-2337ee32466b.png)
![1 2UserPass](https://user-images.githubusercontent.com/51759906/61406086-2aa66c80-a8a9-11e9-8b5c-cf49ccaa67e3.png)
![2 create new](https://user-images.githubusercontent.com/51759906/61406087-2b3f0300-a8a9-11e9-9924-20bcd6586671.png)
![2 1 User Password](https://user-images.githubusercontent.com/51759906/61406088-2b3f0300-a8a9-11e9-857e-61a9dcade2f5.png)
![2 2 show password](https://user-images.githubusercontent.com/51759906/61406089-2b3f0300-a8a9-11e9-9dce-89a1aa4a6bec.png)
![2 3 user padd success](https://user-images.githubusercontent.com/51759906/61406090-2b3f0300-a8a9-11e9-8d47-2f0e833d4cb2.png)
![3 create accesstoken](https://user-images.githubusercontent.com/51759906/61406091-2bd79980-a8a9-11e9-9217-98d6a74a302b.png)
![3 1 access token](https://user-images.githubusercontent.com/51759906/61406092-2bd79980-a8a9-11e9-8463-132623ea75f7.png)
![4 access token success](https://user-images.githubusercontent.com/51759906/61406093-2bd79980-a8a9-11e9-86ed-9473d5787966.png)
![access token detail](https://user-images.githubusercontent.com/51759906/61406095-2c703000-a8a9-11e9-9386-1f6470b42619.png)

**Comment by mi-wang** [comment]
Latest Update:
Invision Link:
https://ibm.invisionapp.com/share/UBNZ3TAXAY2
