### ISSUE TITLE
Script to support migration 0.5.x -> 0.6.1

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#532]
Further to https://github.com/tektoncd/experimental/commit/c74ba9eadbeb61a8c2a00dbd5ca5d8a979e4165c#diff-084976a78fb5ae756cfe352d46b2f4e3L1115 to API group in our EventListener changed, and a 0.6.1 build won't recognise config from the 0.5.x era. See if a script can be written that will migrate config from a 0.5.x install to the 0.6.1 format. 

Note https://github.com/tektoncd/triggers/releases/tag/v0.4.0
> All Triggers resources now use the triggers.tekton.dev API Group.
BREAKING CHANGE: Users will have to delete and recreate resources after updating the API Group. Users will also have to update their EventListener Role resource to point to the triggers.tekton.dev API Group for Triggers resources.

This means that existing TriggerTemplates and TriggerBindings (e.g. associated with previously existing Pipelines) must be accounted for. 

First question: can the old EventListener still be accessed after upgrading Triggers? i.e., 
- Create EventListener with Triggers 0.3.x
- Uninstall Triggers 0.3.x
- Install Triggers 0.4.x
- Is there a `kubectl get eventlistener` command that will still get the original EventListener? e.g. by specifying the old api group? 

If so, we can write a post-install script that fixes it up. If not, we need to obtain it before the uninstall, and then `yq` and reapply it afterwards. Note the EventListeners contain a `status` section that will make it harder to simply get, modify and reapply the old one.

**Comment by ncskier** [comment]
> Is there a kubectl get eventlistener command that will still get the original EventListener? e.g. by specifying the old api group?

`kubectl get eventlisteners.triggers.tekton.dev` will get the "old" EventListener resources, and `kubectl get eventlisteners.tekton.dev` will get the "new" EventListener resources.

> If so, we can write a post-install script that fixes it up. If not, we need to obtain it before the uninstall, and then yq and reapply it afterwards. Note the EventListeners contain a status section that will make it harder to simply get, modify and reapply the old one.

As you said, we might need to do some additional modifications, but we can change the apiVersion to `triggers.tekton.dev` with something like:
```
kubectl get el -oyaml | sed 's/apiVersion: tekton.dev/apiVersion: triggers.tekton.dev/g' | kubectl apply -f -
```
We probably need to do this before removing the old `RESOURCE.tekton.dev` CRDs, because you can't get `eventlisteners.tekton.dev` with `kubectl` after deleting the CRD. (I think that the resources are also deleted)
```
$ kubectl delete crd eventlisteners.tekton.dev
customresourcedefinition.apiextensions.k8s.io "eventlisteners.tekton.dev" deleted
$ kubectl get eventlisteners.tekton.dev
error: the server doesn't have a resource type "eventlisteners"
```

> First question: can the old EventListener still be accessed after upgrading Triggers? i.e.,
> ...
> - Uninstall Triggers 0.3.x

I'm pretty sure that uninstalling a version of Triggers will delete your Triggers resources. Uninstalling a version will delete the Triggers CRDs which deletes your Triggers resources.

**Comment by anneqm** [comment]
@mnuttall @ncskier Reminder that our Dashboard 0.5.2 worked with Triggers 0.2.1 based on  
https://github.com/tektoncd/dashboard#which-version-should-i-useWhich version should I use on the :
- Use the v0.5.2 release for Tekton Pipelines v0.10.x (can display components from Tekton Triggers 0.2.x)
The upgrade scenario we really need is Dashboard 0.5.2 with Triggers 0.2.1.

**Comment by ncskier** [comment]
So I tested this upgrading an example EventListener from Triggers v0.3.1 to v0.4.0 and from v0.2.1 to v0.4.0.

```yaml
# 1. Install new version of Triggers

kubectl apply -f https://github.com/tektoncd/triggers/releases/download/v0.4.0/release.yaml

# 2. Upgrade the Triggers resources to apiVersion triggers.tekton.dev

for ns in $(kubectl get namespaces --no-headers -o custom-columns=":metadata.name"); do

  # EventListeners
  for el in $(kubectl get eventlisteners.tekton.dev -n $ns --no-headers -o custom-columns=":metadata.name"); do
    echo "'$ns' - upgrade eventlistener '$el' to triggers.tekton.dev"
    kubectl get eventlisteners.tekton.dev -n $ns $el -oyaml | yq w - apiVersion triggers.tekton.dev/v1alpha1 | kubectl apply -n $ns -f -
  done

  # TriggerTemplates
  for tt in $(kubectl get triggertemplates.tekton.dev -n $ns --no-headers -o custom-columns=":metadata.name"); do
    echo "'$ns' - upgrade triggertemplate '$tt' to triggers.tekton.dev"
    kubectl get triggertemplates.tekton.dev -n $ns $tt -oyaml | yq w - apiVersion triggers.tekton.dev/v1alpha1 | kubectl apply -n $ns -f -
  done

  # TriggerBindings
  for tb in $(kubectl get triggerbindings.tekton.dev -n $ns --no-headers -o custom-columns=":metadata.name"); do
    echo "'$ns' - upgrade triggerbinding '$tb' to triggers.tekton.dev"
    kubectl get triggerbindings.tekton.dev -n $ns $tb -oyaml | yq w - apiVersion triggers.tekton.dev/v1alpha1 | kubectl apply -n $ns -f -
  done

done

# ClusterTriggerBindings
for ctb in $(kubectl get clustertriggerbindings.tekton.dev -n $ns --no-headers -o custom-columns=":metadata.name"); do
  echo "upgrade clustertriggerbinding '$ctb' to triggers.tekton.dev"
  kubectl get clustertriggerbindings.tekton.dev $ctb -oyaml | yq w - apiVersion triggers.tekton.dev/v1alpha1 | kubectl apply -f -
done

# 3. Delete the old Triggers tekton.dev CRDs

kubectl delete crd triggerbindings.tekton.dev
kubectl delete crd clustertriggerbindings.tekton.dev
kubectl delete crd triggertemplates.tekton.dev
kubectl delete crd eventlisteners.tekton.dev

```

@mnuttall is this what you're looking for from this issue?

**Comment by mnuttall** [comment]
TODO: Test with webhooks extension.

**Comment by a-roberts** [comment]
Pretty sure @rnapoles-tktn's been working this with @ncskier and some good progress has been made on our end (and it's possibly done from what we own?)

**Comment by anneqm** [comment]
anything left to do on this one?
