### ISSUE TITLE
[helm/dashboard] Forbidden error when attempting to view trigger resources

### ISSUE THREAD

**Issue by paulsteele** [tektoncd/experimental#535]
# Expected Behavior
When using the dashboard helm chart alongside the triggers helm chart, I am expecting to be able to load the "EventListeners, TriggerBindings, ClusterTriggerBindings, and TriggerTemplates" by clicking on their respective tabs through the UI

# Actual Behavior
When using the dashboard helm chart alongside the triggers helm chart, when navigating to "EventListeners, TriggerBindings, ClusterTriggerBindings, or TriggerTemplates" by clicking on their respective tabs through the UI, an error message "Error: Forbidden" appears and no resources are shown. 
# Steps to Reproduce the Problem

1. Install version 0.6.1 of dashboard chart
2. Install version 0.4.0 of triggers chart
3. Navigate to Dashboard url
4. Navigate to "EventListeners" Tab

# Additional Info
the dashboards console logs the following error:
```
{"level":"error","msg":"Error: {kind:Status,apiVersion:v1,metadata:{},status:Failure,message:eventlisteners.triggers.tekton.dev is forbidden: User system:serviceaccount:default:ci-dashboard cannot list resource eventlisteners in API group triggers.tekton.dev at the cluster scope,reason:Forbidden,details:{group:triggers.tekton.dev,kind:eventlisteners},code:403}"}
```
In my testing updating https://github.com/tektoncd/experimental/blob/master/helm/dashboard/templates/clusterrole.yaml#L109 & https://github.com/tektoncd/experimental/blob/master/helm/dashboard/templates/clusterrole.yaml#L238 to be `triggers.tekton.dev` and adding `clustertriggerbindings` to the resources fixed the issue.

**Comment by eddycharly** [comment]
Hi @paulsteele , thanks for raising the issue, i will investigate and let you know ASAP.
Thanks

**Comment by eddycharly** [comment]
I opened a PR to fix the issue.
@paulsteele thanks again for reporting and providing the fix ! 👍

**Comment by eddycharly** [comment]
@paulsteele if you want to give it a try i've set up a helm repository, see here https://github.com/eddycharly/tekton-helm

**Comment by paulsteele** [comment]
Awesome, looks great. Thanks :)
