### ISSUE TITLE
[helm] testing charts deployment

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/experimental#544]
## Context

This issue is part of a larger effort towards getting official helm charts for Tekton components.

The discussion here is about **testing charts** before a PR can be merged as safely as possible.

Helm provides a tool to ease testing (https://github.com/helm/chart-testing) that helps linting and installing a chart.

On top of that helm has a concept of tests (in the sense of functional testing), see https://helm.sh/docs/topics/chart_tests/.

### Tooling

What platform/tools do we want to use to integrate tooling ?

It will have to be automated, and support reporting results to github.
Every pull request should therefore have a status describing the test success/failure.

Available choices:
- Prow only
- Tekton only
- Prow + Tekton
- Github actions
- Travis, circle ci, etc...

### Cluster for testing

What type of cluster to use to run the tests ?

Choices will probably depend on the chosen tool but it could be one of:
- kind (requires docker so probably dind if run inside a k8s cluster)
- external cluster taken from a pool (boskos ?)

---

Please feel free to discuss, give opinions or provide feedback to help taking the best decision.

Thanks.

/cc @afrittoli @vdemeester

**Comment by eddycharly** [comment]
## Tooling

I don't have a preference, listing pros/cons from my POV:

- Prow only
_pros_: we already have a prow instance, there are a number of prow jobs already running (lint, docs, version checks)
_cons_: potentially not adapted for kind (holds true for other k8s based platforms too)

- Tekton only
_pros_: we already have a tekton instance, maybe more inline with the long term goals
_cons_: potentially not adapted for kind (holds true for other k8s based platforms too)

- Prow + Tekton
_pros_: we already have prow and tekton running
_cons_: triggering tekton from prow is not well supported (our prow version is not recent)

- Github actions
_pros_: zero maintenance, all done on github side, free
_cons_: not consistent with other Tekton projects, more complex access management

- Travis, circle ci, etc...
_pros_: zero maintenance, free
_cons_: not consistent with other Tekton projects, more complex access management

## Cluster for testing

I'm used to work with kind so this would be my choice preference because:
- it's fast
- it's easy to set up/tear down
- is well adapted to CI jobs

On the other hand, if running kind from inside a pod is an issue, boskos can be used to acquire a cluster.
I don't know boskos well though, i feel like it will be heavy weight but it's certainly feasible.

**Comment by eddycharly** [comment]
Closing. There was almost no feedback during the last 2/3 months, probably a sign of low interest.

Better keep this on the community side for now.
I will be happy to contribute again on this later if interest grows.

**Comment by rouke-broersma** [comment]
We would have been interested in an official helm chart. At the time we did not see these issues so we went ahead with the cd foundation chart. Today we found out that this chart has not been updated to work on k8s 1.22. We would prefer an official chart that is actually kept up-to-date.
