### ISSUE TITLE
[helm] move from experimental to dedicated repository

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/experimental#545]
## Context

This issue is part of a larger effort towards getting official helm charts for Tekton components.

The discussion here is about **moving charts source code out of the experimental repository to its own dedicated one**.

### Maintenance

Who should be responsible of charts maintenance ?
Who should be responsible for cutting releases ?

### Overlap with operator

How helm charts overlap/compare/interact with the existing operator project ?

---

Please feel free to discuss, give opinions or provide feedback to help taking the best decision.

Thanks.

/cc @afrittoli @vdemeester

**Comment by eddycharly** [comment]
Closing. There was almost no feedback during the last 2/3 months, probably a sign of low interest.

Better keep this on the community side for now.
I will be happy to contribute again on this later if interest grows.

**Comment by rouke-broersma** [comment]
We would have been interested in an official helm chart. At the time we did not see these issues so we went ahead with the cd foundation chart. Today we found out that this chart has not been updated to work on k8s 1.22. We would prefer an official chart that is actually kept up-to-date.
