### ISSUE TITLE
Investigate OpenShift Container Platform docker/image registry as a source of events

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#56]
This issue is part of Epic #41: 'docker push'  as a trigger for Tekton pipelines. In this case, we want to know what it will take to trigger Tekton pipelines as a result of operations on the OpenShift Container Platform container registry. As a preliminary investigation we need to know:
- Does the OCP container registry offer an external API?
- Does it support webhooks? What if any events can be subscribed to? 

We don't want to have to poll the registry if there's any way to receive notifications or events from it. We are particularly interested in knowing:
- can we get events or must we poll?
- the names of pushed images
- the tags of pushed images
- the labels on pushed images (from LABEL commands in Dockerfiles)
- what if any other metadata is available 
- what credentials must be provided, and how, in order to use the container registry APIs

**Comment by akihikokuroda** [comment]
So far, I can not find the webhook or REST API for the registry. https://docs.openshift.com/container-platform/4.2/registry/architecture-component-imageregistry.html

**Comment by vtereso** [comment]
So far I found [old (v3.5) Openshift registry documentation](https://docs.openshift.com/container-platform/3.5/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-notifications) that specifies a way to get [webhooks/notifications](https://docs.docker.com/registry/configuration/#notifications) on Docker registry events. I found the codebase for the Openshift registry and they are currently still utilizing the `docker/distribution` standard handlers so this should still work (ref: https://github.com/openshift/image-registry/blob/master/pkg/dockerregistry/server/supermiddleware/app.go#L96 and https://github.com/docker/distribution)./blob/master/registry/handlers/app.go#L159). From what I can tell, neither the `docker/distribution` repo nor the `openshift/image-registry` repo make any references to webhooks s.t. https://docs.docker.com/ee/dtr/admin/manage-webhooks/use-the-api/ is likely not supported. I will continue to see if there are any alternatives as well as proof out the notification configuration approach works using a Triggers endpoint.

**Comment by vtereso** [comment]
I opened an issue and was directed to the new documentation that specifies that [`ImageStreams`](https://docs.openshift.com/container-platform/4.2/openshift_images/image-streams-manage.html#working-with-imagestreams) should best simulate a webhook like behavior. The image registry will create an [ImageStreamMapping](https://github.com/openshift/image-registry/blob/4c72a946991a1e0e67eda2855344bb0d408dc37a/pkg/imagestream/imagestream.go#L310) when updated, which should update the `ImageStream` status (although I couldn't find where this was located). As the [documentation specifies](https://docs.openshift.com/container-platform/4.2/openshift_images/image-streams-manage.html#images-using-imagestream-change-triggers_image-streams-managing), the only mechanism to achieve this is to watch the particular `ImageStream` objects and react. In our case, we could take this image and create/update a deployment through a `Pipeline` or `Task`. In this way, we could separate the CI/CD segments of our pipeline.

**Comment by mnuttall** [comment]
Leaving this open so we can find it, but no further work required at this point.
