### ISSUE TITLE
Does not get presubmit failure for the unit test.

### ISSUE THREAD

**Issue by YolandaDu1997** [tektoncd/experimental#566]
# Expected Behavior

I opened a PR for the new feature. The commit includes new files `write.go` and `write_test.go`. The unit test here actually fails.

# Actual Behavior
But the PR testing doesn't report this error. No failures before review.

# Additional Info
_Originally posted by @wlynch in https://github.com/tektoncd/experimental/pull/564/commits/0ba9dc06814ba55002d94e53e7817c6aa931b16f_

**Comment by wlynch** [comment]
In particular, this is for the `generators` repo. I suspect that all testing is being managed by plumbing, but the config is somewhat opaque. :(
