### ISSUE TITLE
Resolving race condition in watcher in Tekton Results API

### ISSUE THREAD

**Issue by yuege01** [tektoncd/experimental#616]
[Design Proposal](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit)

Currently there is a race condition which could happen when a large number of new TaskRuns are sent to Reconciler in the watcher, for example, during a new TaskRun is being created in results server by a CreateTaskRun  request in Reconciler, another TaskRun could already finish creation and step over this one and take results_id from it.

To clear this issue, we need to design a thread-safe scheme to prevent such race condition to happen.

**Comment by wlynch** [comment]
We're moving forward with an `etag` approach for handling concurrent writes - see https://google.aip.dev/154

This will help us ensure that no 2 writes overlap with each other.

/assign @XinruZhang

**Comment by XinruZhang** [comment]
The Tekton Result API is moved out from the experimental project, and the race condition problem is solved in this PR: https://github.com/tektoncd/results/pull/35.
