### ISSUE TITLE
build and publish results-api images

### ISSUE THREAD

**Issue by ibotty** [tektoncd/experimental#652]
# Expected Behavior
```
skopeo inspect docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/watcher
```
finds an image.

# Actual Behavior
```
Failed to fetch "latest" from request "/v2/tekton-releases/github.com/tektoncd/pipeline/cmd/watcher/manifests/latest
```
because the image is not published (there).

**Comment by wlynch** [comment]
Hi! Sorry about the delay, I only came across this issue recently.

Tekton Results API release details can be found here: https://github.com/tektoncd/results/releases/tag/v0.1.1
