### ISSUE TITLE
Add approval in wait task

### ISSUE THREAD

**Issue by FogDong** [tektoncd/experimental#728]
### Feature request

Right now we have our wait task to support starting the task after a time, but can we start the task after some specific action like `approval`?
In my case, there's some situation that the task needs to be approved by the admin before it gets executed. So before the admin approves the step, the task needs to be paused.

### Use case

ref tektoncd/pipeline#3796

**Comment by ImJasonH** [comment]
As a simple mechanism for implementing approval, you could create a controller that just waits forever for an `Approval`-type Run (i.e., doesn't reconcile or take any action), and expects some other system to update its status to `Done` once approval is granted.

That other system could be an HTTP endpoint, an email/SMS/Slack receiver, etc., with permission to update the Run status.

You could also express rejection of approval by setting the status to `Failed`, track the identity of the approver in the Run status, implement expiring approvals by reintroducing some wait logic from the wait-task, etc.

**Comment by FogDong** [comment]
So we don't want to have `approval` in the wait task, and prefer to let users implement it themselves? 🤔

**Comment by tungamalli** [comment]
During CI/CD in DevOps Workflow there should be Release Manager Approval workflow. Isn`t a standard in any DevOps CI/CD Pipeline.

**Comment by jerop** [comment]
for anyone looking into this, this custom task be useful: https://github.com/automatiko-io/automatiko-approval-task
