### ISSUE TITLE
Sink needs to support operation in non-default namespace

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#77]
Further to https://github.com/tektoncd/experimental/commit/03eeb7c09260928896e5eaa51a982de50e87a7d4 we see this in webhooks-extension/config/sink-kservice.yaml:
```
# TODO: Find better way to provide INSTALL_NAMESPACE since Knative does not support Downward API
  - name: INSTALLED_NAMESPACE
    value: "default"
```
This prevents webhooks from working in non-default namespaces unless one edits that file, which is less than ideal. Is there any way around this in Knative Serving yet? We want to extract ourselves from Knative so don't want to a lot of work in Knative to fix or work around this, we'd definitely like to support non-default namespaces if at all possible.

**Comment by jessm12** [comment]
Added a solution under https://github.com/tektoncd/experimental/pull/94

**Comment by a-roberts** [comment]
We've verified this works fine in the tekton-pipelines namespace now, closing 😄
