### ISSUE TITLE
Reference example given in pipelines-in-pipelines is not working 

### ISSUE THREAD

**Issue by gitcodernitish** [tektoncd/experimental#785]
# Expected Behavior
pipelinerun-with-pipeline-in-pipeline.yaml should work and able to run the pipeline defined as good-morning-good-afternoon
# Actual Behavior
PipelineRun is not able to find the nested pipeline defined in the yaml , The pipeline gets created on the cluster but the PipelineRun refer it in taskref which does not have that task
Error - 
`it contains Tasks that don't exist: Couldn't retrieve Task "good-morning-good-afternoon": tasks.tekton.dev "good-morning-good-afternoon" not found`

# Steps to Reproduce the Problem

1. Install tekton pipeline 
2. Try out example https://github.com/tektoncd/experimental/blob/main/pipelines-in-pipelines/examples/pipelinerun-with-pipeline-in-pipeline.yaml
3. tkn pr <pr-id> logs

# Additional Info

- Kubernetes version: 

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.19.1
Pipeline version: v0.27.2
Dashboard version: v0.14.0
```

**Comment by afrittoli** [comment]
@gitcodernitish I wonder if you enabled [alpha features](https://tekton.dev/docs/pipelines/install/#alpha-features) in your deployment?

**Comment by gitcodernitish** [comment]
Got this working ,  Enabling alpha features was the miss. Thanks @afrittoli . 
Can we add this in the documentation ? I think there can be more user like me who might hit this error.

**Comment by jonashackt** [comment]
I had the same error using the `pipelines-in-pipelines` feature. The references Tekton docs on [Customizing the Pipelines Controller behavior](https://tekton.dev/docs/pipelines/install/#customizing-the-pipelines-controller-behavior) don't really describe how to actually change the feature flag - they just state, that one needs to change a line in the Tekton Pipelines yaml file. If you're asking how to do this "on-the-fly" with `kubectl apply` I wrote a [Q&A on stackoverflow](https://stackoverflow.com/a/70336211/4964553). **TLDR;** installing the officially released Tekton pipelines yaml and enabling alpha features on-the-fly is possile using a piped combination of `curl` and `sed`:

```
curl https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml | sed "s#stable#alpha#g" | kubectl apply -f -
```
