### ISSUE TITLE
[task-loops] Remove max parallel TaskRuns in Task Loops

### ISSUE THREAD

**Issue by jerop** [tektoncd/experimental#804]
today, we provide concurrency controls in looping custom task - https://github.com/tektoncd/experimental/tree/main/task-loops#specifying-concurrency

controlling max parallel taskruns is an issue that came up more broadly for pipelines in https://github.com/tektoncd/pipeline/issues/2591

as we're explore stabilizing this custom task, we need to figure out how to handle this concurrency control

preferably, we can remove it from looping custom tasks then we can explore if and how we want to control max parallel taskruns in general (not just in looping) 

if you're using the concurrency controls in the looping custom task, please share your use cases and experiences

**Comment by pritidesai** [comment]
hey @tomcli, do you utilize `concurrency` feature in a task loop custom task? 

We are designing the proposal for promoting task loop and introducing it as part of the core API. We are looking for the use cases if its being utilized, otherwise we can relay it as a pipeline level feature.

**Comment by Tomcli** [comment]
Thanks @pritidesai, I think the `concurrency` was introduced because the core Tekton API didn't support concurrency within the pipeline scope. If the `concurrency` feature already available within pipelines and able to limit the numbers of `taskrun` and `run`, we can remove this feature in the taskloop custom task.

**Comment by afrittoli** [comment]
I don't think we should remove a feature on the base of a future improvement that, if implemented, might provide a similar functionality.
