### ISSUE TITLE
Cannot install nightly release of pipeline-to-taskrun

### ISSUE THREAD

**Issue by lbernick** [tektoncd/experimental#814]
# Expected Behavior
I can install pipeline-to-taskrun following instructions [here](https://github.com/tektoncd/experimental/tree/main/pipeline-to-taskrun#from-nightly-release).

# Actual Behavior
Installation via kubectl fails with
`error: error parsing https://storage.cloud.google.com/tekton-releases-nightly/pipeline-to-taskrun/latest/release.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context`

# Steps to Reproduce the Problem
`kubectl apply --filename https://storage.cloud.google.com/tekton-releases-nightly/pipeline-to-taskrun/latest/release.yaml --context dogfood`

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-gke.1801", GitCommit:"9352724e36d9c7c35609d30b2696b0de61d23aa0", GitTreeState:"clean", BuildDate:"2021-10-21T21:28:32Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

```
Client version: 0.21.0
Pipeline version: v0.30.0
Triggers version: v0.17.1
Dashboard version: v0.21.0
```

FYI @bobcatfish

**Comment by lbernick** [comment]
FYI @nikhil-thomas since it looks like you may have modified this release pipeline recently in #809

**Comment by nikhil-thomas** [comment]
It looks like the url given the instructions is the `authenticated url`. 

please use this instead `https://storage.googleapis.com/tekton-releases-nightly/pipelines-in-pipelines/latest/release.yaml` 🧑‍💻

**Comment by nikhil-thomas** [comment]
https://github.com/tektoncd/experimental/pull/816
