### ISSUE TITLE
Re-enable tests in webhook_test.go

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/experimental#95]
https://github.com/tektoncd/experimental/pull/93 had to disable three tests in webhook_test.go since they were failing under Prow:

TestMultipleDeletesCorrectData
TestMultipleCreatesCorrectData
TestCreateDeleteCorrectData

Fix these tests so that they pass reliably under Prow.

**Comment by a-roberts** [comment]
Enabled once more, thanks @mnuttall

/meow dream
