### ISSUE TITLE
can I install commit-status-tracker without building it using Go ?

### ISSUE THREAD

**Issue by sibelius** [tektoncd/experimental#971]
https://github.com/tektoncd/experimental/tree/main/commit-status-tracker

is there a simpler way to install this ?

**Comment by sibelius** [comment]
is this similar to this one https://hub.tekton.dev/tekton/task/github-set-status ?

**Comment by AlanGreene** [comment]
Hi @sibelius, to answer the question in the issue title, no I don't believe there's a way to install it without building. There are no "official" releases published for many of the experimental projects. However, see below for reasons not to build it.

For your second question, these are 2 quite different projects:
- `commit-status-tracker`
  - watches the PipelineRuns on your cluster and automatically sets a GitHub commit status on completion to reflect the success / failure
  - ⚠️ However, it relies on support for `PipelineResource`s which were deprecated in Tekton Pipelines v0.30 back in November 2021, and finally removed in v0.45 released February 2023. So `commit-status-tracker` won't work with any recent / currently supported Tekton Pipelines release.
- `github-set-status`
  - this one on the other hand is a `Task` that you can use in your `Pipeline` to set the status as desired.
  - I haven't personally used it, but it does look like it should at least still be compatible with recent Tekton Pipelines releases.
